halo-dev/console

src/api/static.js
src/views/system/developer/tabs/StaticStorage.vue
src/views/system/staticpages/tabs/StaticPagesList.vue

1. 支持静态文件的重命名和编辑，编辑器能够根据文件后缀改变语法高亮
2. 编辑的模态框只能通过Popconfirm退出，防止未保存的内容丢失
3. 模态框Input自动focus
4. StaticStorage.vue的`length="64"`改为`:length="64"`

feat: Support Rename and Edit Static Files (halo #573)

---

src/views/post/components/PostSettingDrawer.vue

针对 halo-issue #763
修改后，当草稿发布时，即是实际点击发布的时间

feat&bug: fix halo issue 763

---

src/components/global.less
src/views/interface/MenuList.vue
src/views/interface/components/MenuTreeNode.vue

1. 删除了菜单的动画效果
2. 当拖拽到菜单底部时，会触发滚动效果
3. 现在拖为子节点会方便那么一点（也不是很完美）
4. 当菜单头不在可视区域时，会触发跟随，不需要拖拽完菜单还需要返回顶部再保存了。

fix(menu): 对菜单做了一些调整和优化。

---

src/views/post/components/PostSettingDrawer.vue
src/views/sheet/components/SheetSettingDrawer.vue

fix: halo-dev/halo#1157

---

src/config/router.config.js
src/core/lazy_lib/components_use.js
src/layouts/PageView.vue
src/styles/global.less
src/views/dashboard/Dashboard.vue
src/views/interface/ThemeList.vue
src/views/post/CategoryList.vue
src/views/post/PostEdit.vue
src/views/post/PostList.vue
src/views/post/TagList.vue
src/views/sheet/SheetEdit.vue
src/views/sheet/SheetList.vue
src/views/sheet/independent/JournalList.vue
src/views/sheet/independent/LinkList.vue
src/views/sheet/independent/PhotoList.vue

pref: optimize the layout of the post editing page.

---

src/api/log.js
src/components/Login/LoginForm.vue
src/views/user/Profile.vue

fix: Unable to redirect the 2FA page by pressing ENTER

---

.editorconfig
package-lock.json
package.json
src/components/Codemirror/Codemirror.vue
src/styles/global.less
src/views/interface/ThemeEdit.vue
src/views/system/developer/DeveloperOptions.vue
src/views/system/developer/tabs/RuntimeLogs.vue
src/views/system/developer/tabs/StaticStorage.vue
vue.config.js
yarn.lock

升级 Codemirror 版本， Codemirror 6 拥有更好的扩展性，以及体积大幅降低。

refactor: upgrade codemirror version.

---

src/components/Editor/MarkdownEditor.vue
src/mixins/mixin.js
src/styles/global.less
src/views/post/PostEdit.vue
src/views/sheet/SheetEdit.vue

自动计算文章编辑器高度，编辑器始终占用窗口剩下的区域高度。
Close #347 #343

perf: automatically calculate post editor height.

---

src/components/Attachment/AttachmentSelectDrawer.vue
src/styles/global.less
src/views/attachment/AttachmentList.vue
src/views/attachment/components/AttachmentDrawer.vue

附件使用背景图显示，有一定的自适应性，不会因为图片高宽比例差距大而导致图片预览体验差
旧
新

Refine image style in attachment page

---

.github/auto_assign.yml

chore: disable automatic addition of assignees in pull requests

---

package.json
pnpm-lock.yaml
src/components/Input/AttachmentInput.vue
src/components/index.js
src/config/router.config.js
src/core/lazy_lib/components_use.js
src/layouts/PageView.vue
src/views/interface/ThemeList.vue
src/views/interface/ThemeSetting.vue
src/views/interface/components/ThemeDeleteConfirmModal.vue
src/views/interface/components/ThemeLocalUpgradeModal.vue
src/views/system/About.vue

1. 提供主题设置的路由和菜单。从菜单进入主题设置默认加载当前激活主题。
2. 取消抽屉式的主题设置界面。
3. 提供主题的基本信息展示。

refactor: theme setting page

---

src/components/Input/AttachmentInput.vue
src/views/post/CategoryList.vue
src/views/post/TagList.vue
src/views/system/optiontabs/GeneralTab.vue

在 https://github.com/halo-dev/halo-admin/pull/380 中创建了 AttachmentInput 组件，此 PR 将所有用到输入框选择附件的地方都替换为此组件，减少重复代码。

refactor: input attachment selection uniformly uses AttachmentInput component

---

package.json
pnpm-lock.yaml
src/components/Editor/MarkdownEditor.vue
src/views/post/PostEdit.vue
src/views/sheet/SheetEdit.vue

1. 移除左上角附件库按钮，入口修改为编辑器的图片按钮。
Video：
https://user-images.githubusercontent.com/21301288/150944237-9a4f72b5-af3d-401a-9872-9a3f27f78394.mp4

refactor: the way to select images for post editing

---

src/views/interface/components/MenuTreeNode.vue

1. 修复移动菜单项到其他分组的时候，导致子菜单丢失的问题。
2. 暂时移除复制到其他分组的功能，暂时没办法解决子菜单关联的问题。
Close #363

fix: moving menu team causes submenus to be lost 

---

src/components/Attachment/AttachmentDetailModal.vue
src/components/Input/AttachmentInput.vue
src/components/Post/MetaEditor.vue
src/components/Tools/Logo.vue
src/styles/global.less
src/views/comment/components/CommentTab.vue
src/views/comment/components/TargetCommentTree.vue
src/views/dashboard/Dashboard.vue
src/views/interface/components/MenuInternalLinkSelector.vue
src/views/interface/components/MenuTreeNode.vue
src/views/post/CategoryList.vue
src/views/post/PostList.vue
src/views/sheet/components/CustomSheetList.vue
src/views/sheet/components/IndependentSheetList.vue
src/views/sheet/independent/JournalList.vue
src/views/sheet/independent/LinkList.vue
src/views/system/About.vue
src/views/system/developer/tabs/OptionsList.vue
src/views/system/developer/tabs/StaticStorage.vue
src/views/user/ResetPassword.vue

使用 `<a-button type="link" />` 代替 `<a href="javascript:void(0);"></a>`

refactor: use the a-button component instead of the link button

---

src/views/post/components/PostSettingModal.vue
src/views/sheet/components/SheetSettingModal.vue

|before|after |
|![image](https://user-images.githubusercontent.com/21301288/151551947-74337ce9-d196-46cb-87cd-6a9a61421a07.png)|![image](https://user-images.githubusercontent.com/21301288/151551822-350af456-9801-40e5-84b3-0187f9484267.png)|
移除按钮不是很有必要，可以用输入框的 clear 图标代替。

refactor: remove the button to remove the thumbnail from the post settings

---

src/components/Attachment/AttachmentSelectModal.vue
src/views/attachment/AttachmentList.vue

重构附件管理批量操作的逻辑。
https://user-images.githubusercontent.com/21301288/153351069-841a7a39-e75b-4c16-b022-3b8d69b84717.mp4

refactor: refactoring the batch operation logic of attachment management

---

src/components/SettingDrawer/SettingDrawer.vue
src/config/defaultSettings.js
src/store/modules/app.js

1. 默认布局修改为左边菜单的布局。
2. 开启左侧菜单布局的时候，自动设置为左侧菜单固定。
3. 开启顶部菜单布局的时候，自动设置顶部菜单固定。
see https://deploy-preview-441--adoring-jang-01641c.netlify.app/

Refactor admin layout settings

---

package.json
pnpm-lock.yaml
src/views/post/PostEdit.vue
src/views/post/PostList.vue

#438 
1. 取消保存草稿的按钮，后续改为在文章设置中提供选项。
2. 支持显示当前是否有未发布内容的特性。
3. 优化预览功能。
依赖于 https://github.com/halo-dev/halo/pull/1617 ，需要等待此 PR 合并。

refactor: post editing

---

src/views/sheet/SheetEdit.vue
src/views/sheet/components/CustomSheetList.vue

#438 
1. 取消保存草稿的按钮，后续改为在页面设置中提供选项。
2. 支持显示当前是否有未发布内容的特性。
3. 优化预览功能。
依赖于 https://github.com/halo-dev/halo/pull/1617 ，需要等待此 PR 合并。

refactor: sheet editing

---

src/views/post/PostList.vue
src/views/sheet/components/CustomSheetList.vue

点击用于提示 “当前有内容已保存，但还未发布。” 的图标时，支持进入编辑页面。

feat: support click on the tip icon to go to edit page

---

package.json
pnpm-lock.yaml
src/views/post/PostEdit.vue
src/views/post/components/PostSettingModal.vue
src/views/sheet/SheetEdit.vue
src/views/sheet/components/SheetSettingModal.vue

文章渲染后内容改为由编辑器提供。
等待 https://github.com/halo-dev/halo/pull/1668 合并。

refactor: post rendered content changed to be provided by editor

---

src/views/post/components/PostSettingModal.vue

before: 
after:
1. 缩小缩略图预览。
2. 保存和关闭按钮交换位置。

perf: optimize the PostSettingModel component style

---

src/views/sheet/SheetEdit.vue
src/views/sheet/components/CustomSheetList.vue
src/views/sheet/components/SheetSettingModal.vue

before:
after:
1. 缩小缩略图预览。
2. 保存和关闭按钮交换位置。
3. 更改部分命名错误。

perf: optimize the SheetSettingModel component style

---

src/components/SettingDrawer/setting.js

chore: modify the cdn address of the less dependency

---

src/components/Attachment/AttachmentSelectModal.vue
src/views/attachment/AttachmentList.vue

fix: attachment list can't to display images with space path

---

src/App.vue
src/components/GlobalHeader/GlobalHeader.vue
src/components/SettingDrawer/SettingDrawer.vue
src/components/Tools/Logo.vue
src/layouts/BasicLayout.vue
src/store/getters.js
src/store/modules/app.js

Close #482
1. 优化折叠菜单时，Logo 和 菜单动画不同步的问题。
2. 折叠菜单时，缩小 Logo。
3. 缓存折叠菜单状态。
before:
after:

perf: optimize the experience of collapsing the menu

---

src/router/guard/permissionGuard.js
src/store/getters.js
src/store/modules/app.js
src/store/modules/option.js
src/views/system/Installation.vue
src/views/user/Login.vue

优化判断是否初始化的逻辑，修改为每次页面加载只请求一次，切换路由不再请求。
see https://github.com/halo-dev/halo/issues/1723#issuecomment-1062500779

perf: optimize the logic for determining whether to initialize

---

src/components/Attachment/AttachmentSelectModal.vue
src/views/attachment/AttachmentList.vue
src/views/sheet/independent/PhotoList.vue

修复附件列表分页之后，可能会导致无法正常更新图片 dom 导致图片显示为上一页图片的问题。

fix: the attachment list image is not updated after paging

---

src/views/post/CategoryList.vue

fix: clear the verification result when editing the category directory.

---

src/components/Input/AttachmentInput.vue
src/views/user/Profile.vue

个人资料的头像支持输入链接来修改。在 1.5.0 重构附件选择的时候丢失了设置 Gravatar 头像的功能，现使用此 PR 代替。

feat: update avatar support to modify the avatar link

---

package.json
pnpm-lock.yaml
src/components/Editor/MarkdownEditor.vue
src/core/constant.js
src/views/dashboard/components/JournalPublishCard.vue
src/views/sheet/independent/JournalList.vue

日志内容修改为由前端渲染并保存。
需等待 js-sdk 发布版本。

refactor: journal editing using the markdown editor

---

package.json
pnpm-lock.yaml

1. 修复嵌套列表语法的渲染问题。
2. 添加 attrs 和 mark 语法的插件。
3. 优化列表语法的编写，可以自动添加序号。
4. 添加打开图片选择的快捷键。
5. 统一使用 [@halo-dev/markdown-renderer](https://github.com/halo-dev/editor/commit/5d8118bbf218ecda4931d94f55b414f9de30b23c) 库进行 Markdown 渲染。

chore: bump @halo-dev/editor to 3.0.0-alpha.3

---

.eslintrc.cjs
.gitignore
histoire.config.ts
package.json
pnpm-lock.yaml
src/components/base/button/Button.story.vue
src/components/base/button/Button.vue
src/components/base/button/index.ts
src/components/base/button/interface.ts

histoire，可以理解为组件开发的 playground 或者编写文档。相对于 storybook 来说，它原生支持 Vite 生态。
see https://github.com/histoire-dev/histoire

chore: add histoire support

---

src/components/Comment/CommentListView.vue
src/components/Comment/TargetCommentListModal.vue
src/components/Comment/TargetCommentTreeNode.vue
src/components/Tools/HeaderComment.vue
src/components/Tools/HeaderCommentTab.vue
src/styles/global.less
src/views/comment/CommentList.vue
src/views/comment/components/CommentTab.vue

待审核评论弹框点击评论支持进入评论管理。
Closes #508 

feat: auditing comments modal support click into the comment management

---

OWNERS

The OWNERS file is for prow only. See https://www.kubernetes.dev/docs/guide/owners/ for more.

chore: create OWNERS

---

src/views/interface/components/MenuInternalLinkSelector.vue

- 修复 #519 提到的问题
- 并修复附近同类型问题
Fix #519

Fix the problem of failure to create menu based on internal preset links

---

package.json
pnpm-lock.yaml

修复编辑器中使用中文输入法时，候选框遮挡住文字的问题。
macOS：
Windows：
/kind bug
fixes #528 

chore: bump @halo-dev/editor to resolve Chinese IME suggestion list obscures inputted text

---

src/views/post/CategoryList.vue

修复当父分类为加密状态时，超过第二级子分类没有显示加密状态的问题。
before:
after: 
> 此时的 donet 分类为加密。
/kind bug

fix: deep sub-categories not showing has password status

---

src/views/dashboard/Dashboard.vue

fix: the icon style in the dashboard statistics is offset

---

src/views/post/CategoryList.vue

fix: no category in category management does not show empty tips

---

src/components/Category/CategorySelectTree.vue
src/components/Post/PostListView.vue

文章列表的分类筛选支持层级显示和显示是否加密。
before:
after:
/kind feature

perf: categories in the post list filters supports showing whether there is a password or not

---

package.json
pnpm-lock.yaml
vue.config.js

直接编译时生成现成的gzip压缩文件，可以降低服务器动态压缩负载
Closes halo-dev/halo#1833

feat: generate gzip products at build time

---

src/views/system/optiontabs/SmtpTab.vue

**What this PR do**
添加开启starttls的按钮。
后端修改的对应pr为: https://github.com/halo-dev/halo/pull/1861

feat: SMTP support configuration starttls

---

src/router/guard/permissionGuard.js

修复因为缓存数据，重新安装会出现循环进入 install 路由的问题。
fixes: halo-dev/halo#1877
/kind bug
/cherrypick release-1.5

fix: routing loop entry after reinstallation

---

package.json
pnpm-lock.yaml

在 [halo-dev/editor](https://github.com/halo-dev/editor) 的 https://github.com/halo-dev/editor/commit/cac614b46ee261ed3b958dfbb7b6a6868af084b3 提交中修复了重复初始化 codemirror 的问题。
fixes halo-dev/halo#1906
/kind bug

chore: bump @halo-dev/editor to resolve duplicate rendering issue

---

src/components/Category/CategoryCreateModal.vue
src/components/Post/PostSettingModal.vue
src/views/sheet/components/SheetSettingModal.vue
src/views/sheet/independent/components/PhotoFormModal.vue

before:
after:
/kind feature
fixes halo-dev/halo#1919

perf: optimize the layout of some forms on mobile

---

src/components/Attachment/AttachmentDetailModal.vue
src/components/Attachment/AttachmentSelectModal.vue
src/components/Editor/MarkdownEditor.vue
src/components/Input/AttachmentInput.vue
src/components/Post/PostSettingModal.vue
src/views/attachment/AttachmentList.vue
src/views/sheet/components/SheetSettingModal.vue
src/views/sheet/independent/PhotoList.vue
src/views/sheet/independent/components/PhotoFormModal.vue

https://github.com/halo-dev/halo/pull/1874 后端对链接进行encodeURI，前端去除
避免特殊字符的错误
```release-note
None
```
fixes halo-dev/halo#1899 
fixes halo-dev/halo#1918

refactor: remove encodeURI handling of attachment paths.

---

src/store/modules/option.js
src/views/system/optiontabs/AttachmentTab.vue

**What this PR does？**
添加是否去除图片EXIF选项的按钮。
后端修改的对应pr为: https://github.com/halo-dev/halo/pull/1889

feat: Add remove EXIF button

---

package.json
pnpm-lock.yaml

Cherry pick of #584 on release-1.5.
#584: chore: bump editor version to 3.0.5
For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.
```release-note
```

Automated cherry pick of #584: chore: bump editor version to 3.0.5

---

src/views/sheet/independent/JournalList.vue

/kind feature
/area admin
优化日志列表设置公开/隐藏状态的方式
Fixes https://github.com/halo-dev/halo/issues/2301
```release-note
优化日志列表设置公开/隐藏状态的方式
```

feat: add buttons that update journal type directly

---

src/views/user/Profile.vue

修改用户头像时提交表单只更新头像字段;
[Fixes个人资料修改头像 #2450](https://github.com/halo-dev/halo/issues/2450)
ruibaby
之前: 修改头像 需要点击修改资料的保存按钮才可以保存新头像；
现在: 修改头像确定后直接保存新头像;
```release-note
NONE
```

perf: update directly after selecting an avatar

---

src/components/image/LazyImage.vue

/kind bug
/milestone 2.0
修复在生产模式下，附件列表的图片无法及时加载的问题。
Fixes https://github.com/halo-dev/halo/issues/2465
测试方式：
1. 本地 console 仓库切换到此 PR 的分支。
2. 构建生产资源：`pnpm build`
3. 参考 https://github.com/halo-dev/halo/pull/2453 配置本地 Halo 代理 Console
4. 访问 <http://localhost:8090/console>，切换到附件页面。
5. 测试上传图片之后是否可以正常加载。
```release-note
None
```

fix: unable to load attachment images in production environment

---

package.json

修复在 Windows 平台下无法正常运行 `build:packages` 等脚本的问题。
Fixes https://github.com/halo-dev/halo/issues/2568
```release-note
NONE
```

fix: `build:packages` script not running on Windows

---

packages/components/src/components.ts
packages/components/src/components/toast/Toast.story.vue
packages/components/src/components/toast/Toast.vue
packages/components/src/components/toast/index.ts
packages/components/src/components/toast/interface.ts
packages/components/src/components/toast/toast-manager.ts

/kind feature
/milestone 2.0
添加 Toast 组件。
特性：
1. 支持相同消息合并。
2. 支持鼠标悬停。
使用方式：
```vue
import { Toast } from '@halo-dev/components'
Toast.success("Hello", { //props })
Toast.info("Hello", { //props })
Toast.warning("Hello", { //props })
Toast.error("Hello", { //props })
```
props：
```ts
export interface ToastProps {
type?: Type;
content?: string;
duration?: number;
closable?: boolean;
frozenOnHover?: boolean;
count?: 0;
onClose?: () => void;
}
```
Toast 方法不仅可以在 Vue 单组件中使用，理论上在任何地方均可使用。
Fixes https://github.com/halo-dev/halo/issues/2534
测试方式：
https://halo-admin-ui-git-fork-ruibaby-feat-toast-component-halo-dev.vercel.app/story/src-components-toast-toast-story-vue?variantId=_default
测试功能是否正常。
```release-note
添加 Toast 组件
```

feat: add toast component

---

packages/components/src/components/avatar/Avatar.story.vue
packages/components/src/components/avatar/Avatar.vue
src/modules/contents/comments/components/CommentListItem.vue
src/modules/contents/comments/components/ReplyListItem.vue
src/modules/system/users/layouts/UserProfileLayout.vue

/milestone 2.0
优化 Avatar 组件在图片加载失败的状态，以及添加加载状态的动画。目前的策略为，如果图片加载异常，那么会取 `alt` 属性生成占位样式。如果没有设置 `alt`，会显示失败的图标。
测试方式：
1. 需要 `pnpm build:packages`
2. 测试修改个人资料的头像，观测不同效果。
3. 访问 https://halo-admin-ui-git-fork-ruibaby-perf-avatar-fallback-halo-dev.vercel.app/story/src-components-avatar-avatar-story-vue?variantId=_default 测试不同参数的效果。
```release-note
优化 Avatar 组件在图片加载失败的状态
```

perf: refine the fallback of the avatar component

---

docs/custom-formkit-input/README.md
src/formkit/formkit.config.ts
src/formkit/inputs/category-checkbox.ts
src/formkit/inputs/category-select.ts
src/formkit/inputs/form.ts
src/formkit/inputs/menu-checkbox.ts
src/formkit/inputs/menu-item-select.ts
src/formkit/inputs/menu-radio.ts
src/formkit/inputs/post-select.ts
src/formkit/inputs/singlePage-select.ts
src/formkit/inputs/tag-checkbox.ts
src/formkit/inputs/tag-select.ts
src/modules/contents/posts/components/PostSettingModal.vue
src/modules/interface/menus/components/MenuItemEditingModal.vue

/kind feature
/milestone 2.0
Ref https://github.com/halo-dev/halo/issues/2526#issuecomment-1273094868
FormKit 文档：https://formkit.com/advanced/custom-inputs
通过扩展 FormKit 的自定义 Input，提供系统常用资源的选择组件。
目前提供如下类型：
- menuCheckbox
- menuRadio
- menuItemSelect
- postSelect
- categorySelect
- tagSelect
- singlePageSelect
- categoryCheckbox
- tagCheckbox
FormKit 组件的使用方式：
```vue
<FormKit
placeholder="请选择文章"
label="文章"
type="postSelect"
validation="required"
/>
```
FormKit Schema 的使用方式：
```yaml
- $formkit: menuRadio
name: menus
label: 底部菜单组
```
Fixes https://github.com/halo-dev/halo/issues/2526
测试方式：
1. 检查后台文章设置弹框的选择分类和标签功能是否正常。
2. 检查后台添加菜单项的功能是否正常。
3. 使用主题或者插件定义 settings.yaml，使用上述任意 input 类型，检查得到的效果和值是否正常。
```release-note
通过扩展 FormKit 的自定义 Input，提供系统常用资源的选择组件。
```

feat: add some formkit custom input for the system core extensions

---

src/components/preview/UrlPreviewModal.vue
src/modules/interface/themes/components/ThemeListModal.vue

/kind feature
/milestone 2.0
Ref https://github.com/halo-dev/halo/pull/2280
支持在 Console 预览主题。
测试方式：进入主题管理，打开已安装主题列表，在每一项的更多按钮即可看到预览主题的按钮。
```release-note
支持在 Console 预览主题。
```

feat: add preview theme support

---

docs/custom-formkit-input/README.md
src/formkit/formkit.config.ts
src/formkit/inputs/code/CodeInput.vue
src/formkit/inputs/code/index.ts

/kind feature
/milestone 2.0
添加 Codemirror 类型的 FormKit 输入框。
在 Vue 单组件中使用：
```vue
<script lang="ts" setup>
const code = ref("")
</script>
<template>
<FormKit
v-model="code"
label="页脚代码"
type="code"
validation="required"
/>
</template>
```
在 FormKit Schema 中使用（插件 / 主题设置表单定义）：
```yaml
- $formkit: code
name: code
label: 页脚代码
```
```release-note
添加 Codemirror 类型的 FormKit 输入框。
```

feat: add formkit custom input of codemirror

---

docs/custom-formkit-input/README.md
src/formkit/formkit.config.ts
src/formkit/inputs/attachment/AttachmentInput.vue
src/formkit/inputs/attachment/index.ts
src/modules/contents/attachments/components/AttachmentGroupList.vue
src/modules/contents/attachments/components/AttachmentSelectorModal.vue
src/modules/contents/pages/components/SinglePageSettingModal.vue
src/modules/contents/posts/categories/components/CategoryEditingModal.vue
src/modules/contents/posts/components/PostSettingModal.vue
src/modules/contents/posts/tags/components/TagEditingModal.vue
src/modules/system/users/components/UserEditingModal.vue

/kind feature
/milestone 2.0
添加选择附件类型的 FormKit 输入框。
在 Vue 单组件中使用：
```vue
<script lang="ts" setup>
const logo = ref("")
</script>
<template>
<FormKit
v-model="logo"
label="Logo"
type="attachment"
validation="required"
/>
</template>
```
在 FormKit Schema 中使用（插件 / 主题设置表单定义）：
```yaml
- $formkit: attachment
name: logo
label: Logo
```
Fixes https://github.com/halo-dev/halo/issues/2558
```release-note
添加选择附件类型的 FormKit 输入框。
```

feat: add formkit custom input of attachment

---

packages/components/package.json
packages/components/src/components/codemirror/Codemirror.story.vue
packages/components/src/components/codemirror/Codemirror.vue
pnpm-lock.yaml

/kind feature
/milestone 2.0
为 Codemirror 组件添加更多预设语言支持，以及支持从外部传入语言包。
目前预设支持：
1. yaml
2. html
3. javascript
4. css
5. json
使用方式：
1. 使用预设
```vue
<script lang="ts" setup>
import { VCodemirror } from "@halo-dev/components"
</script>
<template>
<VCodemirror language="html" />
</template>
```
2. 外部引入
```bash
pnpm install @codemirror/lang-java
```
```vue
<script lang="ts" setup>
import { VCodemirror } from "@halo-dev/components"
import { java } from "@codemirror/lang-java"
</script>
<template>
<VCodemirror :language="java()" />
</template>
```
```release-note
None
```

feat: add preset language support for codemirror components

---

package.json
pnpm-lock.yaml
src/components/global-search/GlobalSearchModal.vue
src/modules/system/plugins/components/PluginListItem.vue
src/modules/system/plugins/layouts/PluginLayout.vue

/milestone 2.0
修改插件 Logo 的使用字段为 `status.logo`。用于适配 https://github.com/halo-dev/halo/pull/2652
Fixes https://github.com/halo-dev/halo/issues/2651
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/2652 分支。
2. 检查插件列表的 Logo 是否显示正常。
```release-note
None
```

refactor: update the field of the plugin logo

---

src/modules/contents/attachments/components/AttachmentDetailModal.vue
src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
src/modules/contents/attachments/components/selector-providers/UploadSelectorProvider.vue

/milestone 2.0
修复一些因使用不当导致的 Vue warn。
```release-note
None
```

fix: some vue warn in browser dev console

---

packages/components/src/components/alert/Alert.vue
src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
src/modules/contents/attachments/components/AttachmentSelectorModal.vue
src/modules/contents/attachments/components/AttachmentUploadModal.vue
src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
src/modules/contents/attachments/composables/use-attachment-policy.ts

/milestone 2.0
优化首次上传附件时，创建存储策略的流程，现在可以直接打开新建策略的表单。
before:
after:
测试方式：
1. 测试在上传弹窗中新建存储策略。
```release-note
优化首次上传附件时，创建存储策略的流程。
```

perf: optimize the creation of attachment storage policies

---

src/modules/interface/menus/components/MenuList.vue
src/views/system/setup-data/menu.json

/kind feature
/milestone 2.0
支持设置主菜单。 适配 https://github.com/halo-dev/halo/pull/2667
Fixes https://github.com/halo-dev/halo/issues/2533
测试方式：
1. Halo 需要使用 https://github.com/halo-dev/halo/pull/2667 分支。
2. 在 Console 的菜单管理新建若干个菜单。
3. 选择一个菜单点击更多按钮，再点击设置为主菜单按钮，检查是否生效。
```release-note
菜单管理支持设置主菜单。 
```

feat: add setup primary menu support

---

package.json
packages/components/src/components/status/StatusDot.vue
packages/components/src/icons/icons.ts
pnpm-lock.yaml
src/constants/labels.ts
src/modules/contents/pages/SinglePageEditor.vue
src/modules/contents/pages/SinglePageList.vue
src/modules/contents/pages/components/SinglePageSettingModal.vue
src/modules/contents/posts/PostEditor.vue
src/modules/contents/posts/PostList.vue
src/modules/contents/posts/components/PostSettingModal.vue
src/modules/dashboard/widgets/RecentPublishedWidget.vue
src/views/system/Setup.vue
src/views/system/setup-data/post.json
src/views/system/setup-data/singlePage.json

/milestone 2.0
重构文章和自定义页面的发布流程。
Ref https://github.com/halo-dev/halo/pull/2659
1. 修改文章、自定义页面标识发布状态的字段名。
2. 修改初始化页面中创建文章和自定义页面的逻辑，取消使用发布接口，改为直接将 `spec.publish` 设置为 `true`
3. 列表支持检测发布状态。
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/2659 分支。
2. Console 需要 `pnpm install && pnpm build:packages`
3. 测试文章和自定义页面的发布、保存等流程。需要完整测试整个流程。
```release-note
None
```

refactor: post and singlePage publishing

---

package.json
pnpm-lock.yaml
src/formkit/formkit.config.ts
src/formkit/theme.ts

/milestone 2.0
移除 FormKit 的 Auto Animate 扩展，因为如果使用了这个扩展，在动态加载表单元素的时候可能会导致 UI 大范围的抖动。而且此扩展比较不可控，无法对其表现进行修改。
before:
```release-note
移除表单中的动画效果
```

refactor: remove formkit auto-animate addon

---

src/components/Tools/Logo.vue

/kind bug
Fixes (https://github.com/halo-dev/halo/issues/1951)
```js
// 判断是否为开发者模式，计数是否小于10，大于10说明正在请求后台。
if (this.options.developer_mode) {
this.$message.info(`当前已启用开发者选项！`)
this.clickCount = 0
} else if (this.clickCount < 10) {
this.$message.info(`再点击 ${10 - this.clickCount} 次即可启用开发者选项！`)
} else if (this.clickCount === 10){
//处理开启逻辑
}else {
this.$message.info('正在启用开发者选项！')
}
```
```release-note
NONE
```

fix: the problem of incorrect hint of opening developer option

---

src/modules/contents/pages/SinglePageEditor.vue
src/modules/contents/posts/PostEditor.vue

/kind feature
/milestone 2.0
文章和独立页面的编辑页面支持 `returnTo` 参数，用于指定发布完成之后的跳转地址。
Fixes https://github.com/halo-dev/halo/issues/2724
测试方式：
1. 选择任意文章进入编辑页面。
2. 在地址栏添加 `&returnTo=http://localhost:8090`
3. 发布文章，观察是否跳转到了 `http://localhost:8090`
```release-note
文章和独立页面的编辑页面支持 `returnTo` 参数。
```

feat: post editor page supports the parameter of returnToView

---

src/modules/contents/attachments/components/AttachmentGroupEditingModal.vue
src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
src/modules/contents/comments/components/ReplyCreationModal.vue
src/modules/contents/pages/components/SinglePageSettingModal.vue
src/modules/contents/posts/categories/components/CategoryEditingModal.vue
src/modules/contents/posts/components/PostSettingModal.vue
src/modules/contents/posts/tags/components/TagEditingModal.vue
src/modules/interface/menus/components/MenuEditingModal.vue
src/modules/interface/menus/components/MenuItemEditingModal.vue
src/modules/system/roles/components/RoleEditingModal.vue
src/modules/system/users/components/UserEditingModal.vue
src/modules/system/users/components/UserPasswordChangeModal.vue
src/views/system/Setup.vue

/milestone 2.0
完善 Console 中表单的验证规则。
Fixes https://github.com/halo-dev/halo/issues/2733
```release-note
完善 Console 中表单的验证规则。
```

perf: adding the necessary validation to the forms

---

packages/components/src/components/entity/Entity.vue
packages/components/src/components/entity/EntityField.vue
src/modules/contents/comments/components/CommentListItem.vue
src/modules/contents/pages/SinglePageList.vue

/milestone 2.0
为 `VEntityField` 组件设置最大宽度，防止内容过多导致 UI 异常。
Fixes https://github.com/halo-dev/halo/issues/2468
测试方式：
1. Console 需要 `pnpm build:packages`
2. 新增任意资源，设置超长的内容，检查列表的样式是否异常。
```release-note
为 `VEntityField` 组件设置最大宽度，防止内容过多导致 UI 异常。
```

perf: set maximum width for entity-field to prevent text overflow

---

package.json

This PR mainly changes version to 1.5.6 in package.json to prepare for the release of 1.5.6.
```release-note
None
```

Change package version to 1.5.6

---

package.json
pnpm-lock.yaml
src/modules/contents/attachments/AttachmentList.vue
src/modules/contents/attachments/components/AttachmentGroupList.vue
src/modules/contents/attachments/composables/use-attachment.ts

/kind feature
/milestone 2.0
附件管理支持通过参数筛选出未分组的附件。适配 https://github.com/halo-dev/halo/pull/2752
Fixes https://github.com/halo-dev/halo/issues/2451
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/2752 分支。
3. 上传若干未分组附件，然后切换到未分组的标签，检查是否查询正确。
4. 将部分附件移动至某个分组，在切换到未分组的标签，检查附件是否正确。
```release-note
附件管理支持未分组的筛选条件。
```

feat: add query attachments by ungrouped parameter support

---

package.json
pnpm-lock.yaml
src/components/editor/DefaultEditor.vue

升级 `@halo-dev/richtext-editor`。
1. 支持在工具栏显示有序列表、无序列表、任务列表的按钮。
2. 为工具栏的按钮添加 tooltip 提示。
3. 在工具栏添加高亮文字的按钮。
4. 在快捷操作列表添加有序列表、无序列表、任务列表、表格、普通文本的操作项。
5. 修复编辑器文字过长导致的布局问题。 Fixes https://github.com/halo-dev/halo/issues/2722
Fixes https://github.com/halo-dev/halo/issues/2722
测试方式：
2. 测试上述功能是否正常。
```release-note
Console 端编辑器的工具栏支持列表、文字高亮等功能。
```

chore: bump @halo-dev/richtext-editor to support more features

---

src/formkit/inputs/post-select.ts
src/formkit/inputs/singlePage-select.ts

FormKit 的文章和自定义页面选择器仅查询可用的文章或自定义页面。
Fixes https://github.com/halo-dev/halo/issues/2790
测试方式：
1. 创建若干文章和自定义页面，然后删除一部分，再将一部分设置为未发布。
2. 进入菜单管理新建菜单项，选择文章或者自定义页面类型。
3. 检查是否包含被删除或者未发布的文章和自定义页面。
```release-note
None
```

perf: formkit post input type only queries the available

---

src/modules/interface/menus/Menus.vue
src/modules/interface/menus/components/MenuEditingModal.vue
src/modules/interface/menus/components/MenuItemEditingModal.vue

/kind bug
修复当菜单项被删除时，没有更新菜单的问题。
Fixes https://github.com/halo-dev/halo/issues/2561
测试方式：
1. 创建一个菜单，添加若干个菜单项。
2. 删除部分菜单项，检查菜单下的菜单项个数是否正确。
```release-note
修复 Console 端当菜单项被删除时，没有更新菜单的问题。
```

fix: the issue that the menu is not updated after the menu item is deleted

---

src/modules/contents/pages/SinglePageList.vue
src/modules/contents/pages/components/SinglePageSettingModal.vue
src/modules/contents/posts/PostList.vue
src/modules/contents/posts/components/PostSettingModal.vue

/milestone 2.0
移除文章设置中内部成员可访问的选项，目前后端没有支持。
```release-note
None
```

refactor: remove the option to make the post internally accessible to members

---

src/components/login/LoginForm.vue

以便用户可以直接输入用户名，不需要再进行额外的鼠标键盘操作
Fixes https://github.com/halo-dev/halo/issues/2779
```release-note
Console 端登录页面支持自动聚焦输入框
```

perf: add autofocus to login username input

---

env.d.ts
src/composables/use-setting-form.ts
src/modules/interface/themes/components/ThemeListModal.vue
src/modules/system/plugins/composables/use-plugin.ts
src/stores/system-states.ts
src/stores/theme.ts
src/utils/api-client.ts

使用 api-client 进行网络请求时，支持添加 `mute` 参数以隐藏异常提示。
Fixes https://github.com/halo-dev/halo/issues/2836
None
```release-note
None
```

feat: api client requests support configuring the mute parameter to hide exception toast

---

src/modules/interface/menus/components/MenuItemEditingModal.vue

/kind bug
修复创建菜单项的时候，自定义链接类型的菜单项无法正常保存名称和链接的问题。
Fixes https://github.com/halo-dev/halo/issues/2816
测试方式：
1. 创建若干自定义类型的菜单项。
2. 检查是否成功保存了名称和连接。
```release-note
修复 Console 端无法正常创建自定义链接类型菜单项的问题。
```

fix: the issue that custom link type menu items cannot be saved normally

---

src/modules/system/plugins/layouts/PluginLayout.vue

/kind bug
修复插件停止时，仍然获取设置选项导致提示失败的问题。
Fixes https://github.com/halo-dev/halo/issues/2866
测试方式：
1. 安装一个插件，将其停止之后检查是否有获取 setting 的请求以及页面上是否有提示。
```release-note
修复在 Console 端停止插件时，仍然获取设置选项导致显示失败提示的问题。
```

fix: plugin failed to get settings when plugin is stopped

---

src/constants/constants.ts
src/constants/labels.ts
src/modules/system/roles/RoleDetail.vue
src/modules/system/roles/RoleList.vue
src/modules/system/roles/composables/use-role.ts

完善用户角色的相关逻辑。适配 https://github.com/halo-dev/halo/pull/2865
1. 支持标识是否是系统保留角色。
2. 根据是否是系统保留角色，禁用修改和删除的操作。
3. 支持判断是否是超级管理员，如果是，默认勾选所有权限。
4. 优化 `包含 N 个权限` 文案的逻辑，超级管理员为 `包含所有权限`。
5. 优化 `基于此角色创建` 的逻辑，判断是否为超级管理员，如果是，需要设置所有角色模板到创建表单。
Fixes https://github.com/halo-dev/halo/issues/2844
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/2865 分支。
2. 测试角色相关的所有功能。
```release-note
完善 Console 端用户角色的相关逻辑
```

feat: refining the logic of user roles

---

src/modules/contents/pages/components/SinglePageSettingModal.vue
src/modules/contents/posts/components/PostSettingModal.vue

/kind bug
修复当文章设置中的发布时间为空字符串时，无法保存的问题。
Fixes https://github.com/halo-dev/halo/issues/2906
测试方式：
1. 进入新建文章页面。
2. 点击右上角发布按钮，填写必要的标题和别名，然后点击保存。
3. 点击右上角设置按钮，切换到高级设置，再次点击保存。
4. 观察是否正常保存。
```release-note
修复 Console 端文章设置中的发布时间为空字符串时，无法保存的问题。
```

fix: cannot save post when the publishTime is blank

---

src/layouts/BasicLayout.vue

/kind bug
Fixes https://github.com/halo-dev/halo/issues/2927
```release-note
None
```

fix: the global search keyboard event is not removed when the component is unmounted

---

packages/components/src/components/entity/Entity.vue

优化 Entity 组件（数据列表）的操作按钮样式。
Fixes https://github.com/halo-dev/halo/issues/2971
before:
after:
None
```release-note
优化 Console 端数据列表的操作按钮样式
```

perf: optimize the operation button style of the entity component

---

package.json
pnpm-lock.yaml
src/modules/interface/themes/ThemeDetail.vue
src/modules/interface/themes/components/components/ThemeListItem.vue
src/modules/interface/themes/composables/use-theme.ts
src/modules/interface/themes/layouts/ThemeLayout.vue
src/modules/system/plugins/components/PluginListItem.vue

/kind feature
支持重置主题和插件的设置选项。适配 https://github.com/halo-dev/halo/pull/2964
Fixes https://github.com/halo-dev/halo/issues/2789
测试方式：
1. 安装若干带有设置选项主题和插件。
2. 进入主题和插件设置，改变部分设置并保存。
3. 重置主题和插件的设置，然后进入设置表单，检查是否已经恢复为了默认。
```release-note
支持重置主题和插件的设置选项。
```

feat: add support for resetting configmap of plugin and theme

---

src/App.vue

修复 `v-tooltip` 指令的元素闪烁问题。
Fixes https://github.com/halo-dev/halo/issues/2994
测试方式：
1. 创建一篇文章，仅保存不发布。
2. 回到文章管理列表，可以看到标题旁边有一个状态点，鼠标移入会显示提示。
3. 观察是否出现闪烁的问题。
```release-note
优化 Console 端状态提示的样式
```

fix: the flickering issue of tooltip

---

docs/extension-points/editor.md
packages/shared/src/index.ts
packages/shared/src/states/editor.ts
packages/shared/src/types/plugin.ts
src/components/editor/DefaultEditor.vue
src/composables/use-editor-extension-points.ts
src/modules/contents/pages/SinglePageEditor.vue
src/modules/contents/pages/layouts/PageLayout.vue
src/modules/contents/posts/PostEditor.vue
src/modules/contents/posts/PostList.vue

/kind feature
添加编辑器的扩展点，用于扩展集成其他编辑器。
定义一个扩展点的方式：
```ts
export default definePlugin({
extensionPoints: {
"editor:create": () => {
return [
{
name: "stackedit",
displayName: "StackEdit",
component: markRaw(StackEdit),
rawType: "markdown",
},
];
},
},
});
```
其中 `component` 字段即编辑器组件对象，需要包含 `raw`、`content` 的 prop。
Fixes https://github.com/halo-dev/halo/issues/2881
目前可用于测试的插件：
1. [plugin-stackedit-1.0.0-SNAPSHOT.jar.zip](https://github.com/halo-dev/console/files/10258488/plugin-stackedit-1.0.0-SNAPSHOT.jar.zip)
2. [plugin-bytemd-1.0.0-SNAPSHOT.jar.zip](https://github.com/halo-dev/console/files/10258490/plugin-bytemd-1.0.0-SNAPSHOT.jar.zip)
测试方式：
1. Console 需要 `pnpm build:packages`。
2. 在 Console 的插件管理上传以上插件。
3. 新建若干文章，使用不同的编辑器。
4. 检查是否能够正常发布和编辑。
5. 检查编辑的时候，是否正确使用了之前的编辑器。
6. 检查主题端是否渲染正常。
一些实现细节： …

feat: add editor extension point

---

src/views/system/Setup.vue

/kind bug
修复首次初始化之后，Console 没有加载已激活主题的问题。
Fixes https://github.com/halo-dev/halo/issues/3018
测试方式：
1. 使用全新的环境
2. 参考 https://docs.halo.run/developer-guide/core/build 构建可执行 JAR。
3. 运行 Halo，初始化之后检查 Console 主题页面是否已经加载了已经激活的主题。
```release-note
修复首次初始化之后，Console 没有加载已激活主题的问题。
```

fix: activated theme not loaded after initialization

---

src/modules/interface/menus/components/MenuEditingModal.vue
src/modules/interface/menus/components/MenuItemEditingModal.vue

新增和修改菜单时，标题都为编辑菜单，存在歧义
Fixes https://github.com/halo-dev/halo/issues/3022
测试方式：新增菜单和菜单项。然后再编辑菜单和菜单项，查看title是否一样
```release-note
None
```

Differentiate the title of adding and editing menu and menu item

---

src/modules/contents/comments/components/ReplyCreationModal.vue

优化评论回复组件的 emoji 数据加载，改为异步的方式。
构建结果对比：
优化前：
优化后：
首次请求对比：
优化前：
优化后：
最终会在打开 emoji 组件的时候才加载 emoji 数据：
Fixes https://github.com/halo-dev/halo/issues/3039
测试方式：
1. 检查回复组件的 Emoji 选择功能是否正常即可。
```release-note
Console 端的评论回复 Emoji 组件数据改为异步加载，优化整体的加载性能。
```

perf: asynchronously load the emoji data of the comment reply component

---

src/composables/use-editor-extension-points.ts

默认编辑器改为异步的形式加载。
优化前后对比：
优化前编译：
优化后编译：
优化前首次加载：
优化后首次加载：
最终会在打开文章编辑页面的时候加载编辑器资源：
> 这个 Gif 的演示做了节流处理来模拟服务器带宽的情况。在带宽不良的情况下会显示加载动画以提示使用者正在加载编辑器。
Fixes https://github.com/halo-dev/halo/issues/3047
测试方式：
1. 插件默认编辑器是否正常加载以及功能是否正常即可。
```release-note
Console 端的默认编辑器改为异步加载，优化整体的加载性能。
```

perf: asynchronously load the default editor

---

src/components/form/AnnotationsForm.vue
src/modules/contents/pages/components/SinglePageSettingModal.vue
src/modules/contents/posts/categories/components/CategoryEditingModal.vue
src/modules/contents/posts/tags/components/TagEditingModal.vue
src/modules/interface/menus/components/MenuItemEditingModal.vue
src/modules/system/users/components/UserEditingModal.vue

/kind feature
为更多模型添加 Annotation Form 的支持。此 PR 包括：
1. 自定义页面。
2. 文章分类。
3. 文章标签。
4. 菜单项。
5. 用户。
此 PR 是对 https://github.com/halo-dev/console/pull/770 的补充。
测试方式：
1. 将一下内容放到任意一个主题下，后缀为 `yaml`，文件名随意。
```yaml
spec:
targetRef:
group: content.halo.run
kind: Post
formSchema:
- $formkit: "text"
name: "download"
label: "下载地址"
- $formkit: "text"
name: "version"
label: "版本"
apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
generateName: annotation-
---
spec:
targetRef:
group: content.halo.run
kind: SinglePage
formSchema:
- $formkit: "text"
name: "download"
label: "下载地址"
- $formkit: "text"
name: "version"
label: "版本"
apiVersion: v1alpha1
kind: AnnotationSetting
metadata:
generateName: annotation-
---
spec:
targetRef:
group: content.halo.run
kind: Category
formSchema:
- $formkit: "text"
name: …
```

feat: add annotations form for more extension

---

src/modules/contents/pages/components/SinglePageSettingModal.vue
src/modules/contents/posts/components/PostSettingModal.vue

/kind bug
修复保存文章设置导致发布时间丢失的问题。
Fixes https://github.com/halo-dev/halo/issues/3080
测试方式：
1. 创建若干文章。
2. 返回到文章管理列表。
3. 打开任意文章的设置。
4. 检查发布时间是否回显，然后保存。
5. 保存之后检查发布时间是否还存在。
```release-note
修复 Console 端保存文章设置导致发布时间丢失的问题。
```

fix: saving an post causes the publish time to be lost

---

src/modules/contents/pages/SinglePageEditor.vue
src/modules/contents/posts/PostEditor.vue

/kind bug
修复编辑旧文章时，没有为文章设置 `content.halo.run/preferred-editor` 的元数据的问题。
Ref https://github.com/halo-dev/halo/issues/3080
测试方式：
1. 在有旧数据的情况下切换到此 PR。
2. 编辑一篇旧的文章后保存。
3. 打开文章设置，检查元数据中是否包含了 `content.halo.run/preferred-editor`
```release-note
None
```

fix: preferred-editor annotation is not set when editing old posts

---

package.json
pnpm-lock.yaml
src/modules/interface/menus/components/MenuItemEditingModal.vue

/kind feature
支持为菜单项设置链接打开方式。 适配：https://github.com/halo-dev/halo/pull/3072
Fixes https://github.com/halo-dev/halo/issues/3063
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/3072 的分支。
3. 创建若干菜单项，并设置打开方式。
4. 检查是否设置正确。
```release-note
菜单项支持设置打开方式
```

feat: add target attribute setting for menu item

---

package.json
pnpm-lock.yaml
src/modules/interface/themes/ThemeDetail.vue
src/modules/interface/themes/components/components/ThemeListItem.vue
src/modules/interface/themes/composables/use-theme.ts

/kind feature
修改主题的 `spec.require` 字段为 `spec.requires`，以及支持显示错误信息。适配：https://github.com/halo-dev/halo/pull/3150
Fixes https://github.com/halo-dev/halo/issues/3088
测试方式：
1. Halo 切换到 https://github.com/halo-dev/halo/pull/3150 分支。
2. Console 需要 `pnpm install`。
3. 修改主题的 `spec.requires`，根据 https://github.com/halo-dev/halo/pull/3150 中的测试条件修改这个值。
4. 检查是否可以显示异常版本信息。
```release-note
Console 端支持显示主题的版本异常信息
```

feat: update theme requires field and supports show failed message

---

src/modules/contents/comments/CommentList.vue

/kind bug
修复后台删除评论后会导致下方头像错误的bug
Fixes https://github.com/halo-dev/halo/issues/3170
```release-note
修复后台删除评论后会导致下方头像错误的bug
```

fix: use comment.metadata.name instead of index as the key of comments list

---

packages/components/src/components/toast/Toast.vue

/kind bug
解决提示信息过长时不能完全展示的问题。
Fixes https://github.com/halo-dev/halo/issues/3163
```release-note
fix: add word break for long toast body
```

fix: add word break for long toast body

---

package.json
pnpm-lock.yaml
src/composables/use-slugify.ts
src/formkit/inputs/category-select/CategorySelect.vue
src/formkit/inputs/tag-select/TagSelect.vue
src/modules/contents/pages/components/SinglePageSettingModal.vue
src/modules/contents/posts/categories/components/CategoryEditingModal.vue
src/modules/contents/posts/components/PostSettingModal.vue
src/modules/contents/posts/tags/components/TagEditingModal.vue

/kind feature
/milestone 2.2.x
文章、独立页面、分类、标签支持自动生成别名。
策略：
1. 仅在创建时会自动根据标题或者名称自动生成别名，编辑时如果需要重新生成，可以点击输入框右侧的按钮。
2. 中文会被转为拼音并用 - 隔开，需要注意多音字的情况，目前无法保证多音字是否符合预期。
3. 使用了 https://www.npmjs.com/package/transliteration 库。
Fixes https://github.com/halo-dev/halo/issues/3171
测试方式：
4. 测试文章、独立页面、分类、标签创建时，是否可以自动设置别名。
5. 测试别名输入框右侧的生成别名按钮是否正常工作。
6. 测试分类和标签选择器创建新分类或标签时，是否正确设置了别名。
```release-note
Console 端的文章、独立页面、分类、标签支持自动生成别名
```

feat: add supports for automatic slug generation

---

package.json
pnpm-lock.yaml
src/modules/contents/pages/SinglePageEditor.vue
src/modules/contents/posts/PostEditor.vue
src/utils/api-client.ts

修改获取文章和自定义页面内容的 API，用于适配：https://github.com/halo-dev/halo/pull/3168
测试方式：
1. 测试文章和自定义页面编辑时，能否正常获取内容即可。
```release-note
None
```

refactor: change api of fetching post and singlepage content

---

packages/components/src/icons/icons.ts
src/modules/index.ts
src/modules/system/actuator/Actuator.vue
src/modules/system/actuator/module.ts
src/modules/system/actuator/types/index.ts

/kind feature
添加 Actuator 信息查看页面。适配 https://github.com/halo-dev/halo/pull/3182
todo:
Fixes https://github.com/halo-dev/halo/issues/3055
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/3182 分支。
2. Console 需要 `pnpm build:packages`
3. 访问 http://localhost:8090/console#/actuator
```release-note
Console 端添加系统信息查看页面
```

feat: add actuator view page

---

packages/components/src/components/codemirror/Codemirror.vue

/kind bug
修复 Console 端 FormKit 的 Code 输入类型宽度异常
Fixes # https://github.com/halo-dev/halo/issues/3227
```release-note
修复 Console 端 FormKit 的 Code 输入框宽度未占满的问题
```

fix: the width of the code input type is not full

---

src/modules/interface/themes/layouts/ThemeLayout.vue
src/modules/system/plugins/layouts/PluginLayout.vue
src/modules/system/settings/layouts/SystemSettingsLayout.vue

优化部分页面 VCard 组件的用法，修复样式问题。
Fixes https://github.com/halo-dev/halo/issues/3226
before:
after:
测试方式：
1. 检查主题详情页面、插件详情页面、系统设置页面的内容区域，底部的圆角是否生效。
```release-note
优化 Console 端主题详情、插件详情、系统设置中卡片组件的样式。
```

perf: improve usage of the card component in some pages

---

src/layouts/BasicLayout.vue

/area console
使左侧菜单栏滚动条不被遮挡
Fixes https://github.com/halo-dev/halo/issues/3272
分为logo、可滚动（搜索、菜单）、用户信息三部分，不妥就关闭这个PR吧
```release-note
完整显示左侧菜单栏滚动条
```

fix: menu scroll bar is blocked

---

src/components/dropdown-selector/CategoryDropdownSelector.vue
src/components/dropdown-selector/TagDropdownSelector.vue
src/components/dropdown-selector/UserDropdownSelector.vue
src/components/global-search/GlobalSearchModal.vue
src/modules/system/roles/RoleList.vue
src/modules/system/users/UserList.vue

优化 Console 端使用 fuse.js 搜索引擎的搜索阈值，解决搜索关键词匹配的问题。
Fixes https://github.com/halo-dev/halo/issues/3289
before:
after:
测试方式：
1. 检查 Console 端全局搜索，以及用户/权限管理的搜索是否符合预期。
```release-note
优化 Console 端全局搜索的匹配规则。
```

perf: improve the indexing threshold for the fuse search engine

---

src/modules/contents/comments/components/CommentListItem.vue
src/modules/contents/comments/components/ReplyListItem.vue

修复评论管理中内容文字过长导致样式异常的问题。
Fixes https://github.com/halo-dev/halo/issues/3294
before:
after:
```release-note
修复 Console 的评论管理中内容文字过长导致样式异常的问题。
```

perf: improve word-break style for comment content

---

src/layouts/BasicLayout.vue
src/main.ts
src/modules/system/roles/RoleList.vue
src/modules/system/users/UserDetail.vue
src/modules/system/users/UserList.vue
src/stores/role.ts

为系统初始化的角色添加显示名称
Fixes https://github.com/halo-dev/halo/issues/3257
测试方式：
1. Halo 需要切换到：https://github.com/halo-dev/halo/pull/3280
2. 检查 Console 端显示的系统角色是否正常。
3. 新建若干自定义角色，检查名称是否正常。
```release-note
优化 Console 端用户角色标识的显示名称。
```

fix: the issue that role display name

---

src/components/login/LoginForm.vue

改进登录异常的提示信息，目前大致分为三种：
1. 用户名或密码错误
2. 跨域或网络请求异常
3. CSRF Token 失效
Fixes https://github.com/halo-dev/halo/issues/3291
测试方式：
1. 进入浏览器控制台清理 Cookie，以测试 CSRF Token 失效的情况。
2. 使用 3000 端口访问 Console，以测试跨域的情况。
3. 观察以上两种情况的登录请求异常提示信息是否符合要求。
```release-note
优化 Console 端登录请求异常的提示
```

perf: improve error message of login

---

packages/api-client/src/.openapi-generator/FILES
packages/api-client/src/api/api-console-halo-run-v1alpha1-user-api.ts
src/modules/system/users/UserList.vue

/kind feature
用户管理列表支持条件筛选和排序，适配：https://github.com/halo-dev/halo/pull/3320
Fixes https://github.com/halo-dev/halo/issues/3290
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/3320 分支。
2. Console 需要 `pnpm build:packages`
3. 测试用户管理的关键词、条件、排序筛选是否工作正常。
```release-note
Console 端的用户列表支持条件筛选和排序。
```

feat: user management supports conditional filtering and sorting

---

src/components/editor/DefaultEditor.vue

默认编辑器的大纲在没有内容的时候支持显示空状态的提示。
Fixes https://github.com/halo-dev/halo/issues/3335
```release-note
Console 端默认编辑器的大纲列表支持显示空状态
```

perf: default editor's toc supports showing empty states

---

src/components/upload/UppyUpload.vue
src/modules/system/plugins/components/PluginUploadModal.vue

/kind feature
安装已存在插件时，支持提示和升级插件。
Fixes https://github.com/halo-dev/halo/issues/3164
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/3350 分支。
2. 在插件为 deployment 模式下启动 Halo。
3. 安装任意一个插件，然后继续上传安装相同插件。
4. 观察是否提示升级此插件。
```release-note
Console 端安装已存在插件时，支持提示并升级插件。
```

feat: prompt to upgrade plugin when installing existing plugin

---

src/modules/system/actuator/Actuator.vue
src/modules/system/actuator/types/index.ts

/kind feature
支持在系统概览页面显示数据库信息。
Fixes https://github.com/halo-dev/halo/issues/3263
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/3351 分支。
2. 进入系统概览页面，检查是否有数据库信息。
```release-note
Console 端的系统概览页面支持显示数据库信息
```

feat: add supports for display database info in actuator page

---

src/layouts/BasicLayout.vue

支持保存侧板滚动条位置，防止切换路由时侧边栏的抖动。
Fixes https://github.com/halo-dev/halo/issues/3240
before:
after:
测试方式：
1. 调整浏览器高度，让侧边栏菜单区域出现滚动条。
2. 测试点击底部的任意菜单项，跳转页面之后，观察滚动条是否与之前的位置保持一致。
```release-note
Console 端侧边栏滚动条支持缓存位置，防止切换路由时重置滚动条位置。
```

perf: add supports for storing navbar position

---

package.json
pnpm-lock.yaml
src/main.ts
src/modules/system/plugins/PluginDetail.vue
src/modules/system/plugins/PluginList.vue

使用 [TanStack Query](https://github.com/TanStack/query) 重构插件管理列表的数据请求相关逻辑。
Ref https://github.com/halo-dev/halo/issues/3360
测试方式：
2. 插件管理页面，安装若干插件。
3. 测试分页、条件筛选等逻辑是否正常。
```release-note
None
```

refactor: use tanstack query to refactor plugins fetching

---

src/components/form/AnnotationsForm.vue

/kind bug
/milestone 2.3.x
/area console
Fixes https://github.com/halo-dev/halo/issues/3357
测试使用主题/插件自定义的元数据信息，是否能够在 console 中显示默认值。
```release-note
使用主题/插件配置的元数据将能够展示默认值
```

fix: default value of formkit schema is not initialize in annotation form

---

src/modules/system/users/layouts/UserProfileLayout.vue

因为暂时不太好为用户设置个人资料背景图片，所以暂时移除个人资料页面的默认背景。
Fixes https://github.com/halo-dev/halo/issues/2851
None
```release-note
移除 Console 端个人资料页面的默认背景图片
```

refactor: remove default cover from user profile page

---

src/components/dropdown-selector/CategoryDropdownSelector.vue
src/components/dropdown-selector/TagDropdownSelector.vue
src/formkit/inputs/category-select/CategorySelect.vue
src/formkit/inputs/category-select/components/CategoryTag.vue
src/formkit/inputs/category-select/components/SearchResultListItem.vue
src/formkit/inputs/tag-select/TagSelect.vue
src/modules/contents/posts/DeletedPostList.vue
src/modules/contents/posts/PostList.vue
src/modules/contents/posts/categories/CategoryList.vue
src/modules/contents/posts/categories/composables/use-post-category.ts
src/modules/contents/posts/categories/utils/index.ts
src/modules/contents/posts/tags/TagList.vue
src/modules/contents/posts/tags/composables/use-post-tag.ts
src/modules/contents/posts/widgets/RecentPublishedWidget.vue

使用 [TanStack Query](https://github.com/TanStack/query) 重构文章相关数据请求的相关逻辑。
Ref https://github.com/halo-dev/halo/issues/3360
测试方式：
1. 测试文章相关联的页面，包括文章管理、分类、标签。
```release-note
None
```

refactor: use tanstack query to refactor post-related fetching

---

src/composables/use-slugify.ts

/kind bug
修复新建分类和标签之后再次打开表单，别名显示为 undefined 的问题。
Fixes https://github.com/halo-dev/halo/issues/3382
测试方式：
1. 新建分类或者标签，创建完成之后再次打开创建表单，检查别名是否还为 undefined。
```release-note
修复 Console 端新建分类和标签之后再次打开表单，别名显示为 undefined 的问题。
```

fix: the issue that the useSlugify hook may cause the value to be undefined

---

src/modules/contents/attachments/composables/use-attachment.ts

/kind feature
编辑器支持选择附件作为链接插入。目前在附件库选择附件时，如果非图片、视频、音频，那么就会作为链接插入。
Fixes https://github.com/halo-dev/halo/issues/2673
测试方式：
1. 测试从附件库选择非图片、视频、音频的时候是否会作为链接插入即可。
```release-note
Console 端默认编辑器支持以链接的形式插入非图片、音视频的附件。
```

feat: editor supports selecting attachments to be inserted as links

---

src/components/editor/DefaultEditor.vue

禁止在编辑器粘贴 Excel 表格时，将表格转为图片的形式上传。
Fixes https://github.com/halo-dev/halo/issues/3348
before:
after:
测试方式：
1. 使用 Excel 或者 macOS 下的 Numbers 创建一个表格。
2. 复制整个表格或者某几个单元格，并粘贴到 Halo 的编辑器。
3. 观察是否有将内容转为图片并上传。
```release-note
Console 端禁止在编辑器粘贴 Excel 表格以图片的形式上传。
```

perf: disable the editor from pasting excel tables as pictures

---

packages/api-client/src/models/plugin-status.ts
src/modules/system/plugins/components/PluginListItem.vue
src/modules/system/plugins/layouts/PluginLayout.vue

1. 插件停止时支持配置插件设置项。
2. 修改插件异常信息的获取方式。
适配：https://github.com/halo-dev/halo/pull/3355
Fixes https://github.com/halo-dev/halo/issues/3352
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/3355 分支。
2. Console 需要 `pnpm build:packages`
3. 根据 https://github.com/halo-dev/halo/pull/3355 中的描述进行测试。
```release-note
None
```

refactor: support configuring plugin when the plugin is stopped

---

src/modules/interface/themes/components/components/ThemeListItem.vue
src/modules/interface/themes/components/preview/ThemePreviewListItem.vue

当主题已经启用时，隐藏启用的按钮。
Fixes https://github.com/halo-dev/halo/issues/3059
测试方式：
1. 在主题管理列表检查已启用主题是否还有启用按钮即可。
```release-note
Console 端主题管理列表隐藏已启用主题的启用按钮。
```

perf: hide active button when theme is activated

---

src/components/dropdown-selector/UserDropdownSelector.vue

/kind bug
修复用户筛选列表在搜索之后无法正常加载头像的问题。
Fixes https://github.com/halo-dev/halo/issues/3361
测试方式：
1. 创建若干用户并设置头像。
2. 打开文章管理的用户筛选项，尝试输入关键词搜索，观察搜索出的用户头像是否加载正常。
```release-note
修复 Console 端用户筛选项，输入关键词搜索之后无法加载头像的问题。
```

fix: user filter list will fail to load the avatar after searching

---

packages/api-client/src/api/api-console-halo-run-v1alpha1-plugin-api.ts
packages/api-client/src/base.ts
packages/api-client/src/models/plugin-status.ts
src/views/system/Setup.vue

/kind feature
支持在初始化页面安装预设插件。适配：https://github.com/halo-dev/halo/pull/3394
Fixes https://github.com/halo-dev/halo/issues/3120
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/3394
2. Console 需要 `pnpm build:packages`
3. 根据 https://github.com/halo-dev/halo/pull/3394 中的提示，将需要预设的插件放置到 `src/main/resources/presets/plugins`
4. 使用全新的环境进行初始化，完成之后进入插件管理检查是否正常安装了预设插件
```release-note
Console 端支持在初始化页面安装预设插件。
```

feat: add supports for initialize preset plugins

---

src/modules/contents/attachments/AttachmentList.vue

/kind bug
修复附件管理默认分页条数不正确的问题，应该是在 https://github.com/halo-dev/console/pull/878 中测试分页之后没有改回原来的值导致的。
Fixes https://github.com/halo-dev/halo/issues/3406
测试附件管理页面默认分页条数是否为 60 即可。
```release-note
None
```

fix: incorrect default pagination number of attachment list

---

src/modules/contents/attachments/composables/use-attachment.ts

/kind bug
修复默认编辑器从附件库选择非图片、音视频的附件，以链接的形式插入之后得到的链接不正确的问题。
Fixes https://github.com/halo-dev/halo/issues/3408
before:
after:
测试方式：
1. 上传若干 zip 格式附件。
2. 在编辑器中选择这些附件并插入，检查链接是否正确。
```release-note
None
```

fix: get the wrong link after selecting an attachment

---

src/modules/contents/comments/CommentList.vue
src/modules/contents/comments/components/CommentListItem.vue

使用 [TanStack Query](https://github.com/TanStack/query) 重构评论管理相关数据请求的相关逻辑。
Ref https://github.com/halo-dev/halo/issues/3360
测试方式：
1. 测试评论管理列表的数据请求 + 条件筛选无异常即可。
```release-note
None
```

refactor: use tanstack query to refactor comment-related fetching

---

src/views/system/Setup.vue

隐藏在初始化页面启用插件时的错误提示，因为会重试三次，所以不需要提示。
```release-note
None
```

perf: mute the start plugin request in setup page

---

src/modules/contents/pages/SinglePageEditor.vue
src/modules/contents/posts/PostEditor.vue

> **Warning**
>
> 此 PR 的改动来自：<https://github.com/halo-dev/halo/pull/3468>
> 因为目前 Console 仓库已经合并到 Halo 主仓库，但主仓库的 release-2.3 分支不包含 Console，所以如果需要发布 2.3.x 的 patch 版本，依旧需要在此仓库修改。
/kind bug
/milestone 2.3.2
在编辑器初始化前赋值，可以保证缓存的历史数据附在StackEdit的url上。
Fixes (https://github.com/halo-dev/halo/issues/3105)
+ 新建文章，切换为 StackEdit 编辑器
+ 输入一些内容保存/发布文章
+ 回到文章列表，重新点进刚才的文章
+ 重复步骤3，输入的内容还在
```release-note
修复 Console 端在使用三方编辑器插件编辑文章时可能出现无法加载内容的问题。
```

fix: the issue of blank content when opening a saved post in StackEdit editor plugin for editing

---

src/modules/contents/pages/SinglePageEditor.vue
src/modules/contents/posts/PostEditor.vue

> **Warning**
>
> 此 PR 的改动来自：<https://github.com/halo-dev/halo/pull/3516>
> 因为目前 Console 仓库已经合并到 Halo 主仓库，但主仓库的 release-2.3 分支不包含 Console，所以如果需要发布 2.3.x 的 patch 版本，依旧需要在此仓库修改。
/kind bug
/milestone 2.3.2
修复在新建文章时，首次切换编辑器后没有设置内容 rawType 资源为对应编辑器类型的问题。
Fixes #3512 
测试方式：
1. 安装任意一个编辑器插件，比如：https://github.com/halo-sigs/plugin-stackedit
1. 新建文章，选择安装的编辑器。
1. 发布文章。
1. 卸载或者停止编辑器。
1. 重新编辑刚刚创建的文章，如果提示 `未找到符合 markdown 格式的编辑器，请检查是否已安装编辑器插件` 则代表正常。
```release-note
修复在新建文章时，首次切换编辑器后没有设置内容 rawType 资源为对应编辑器类型的问题。
```

fix: the rawType of Content was not updated when switching editors

---

src/modules/contents/pages/components/SinglePageSettingModal.vue
src/modules/contents/posts/components/PostSettingModal.vue
src/modules/contents/posts/components/__tests__/PostSettingModal.spec.ts

> **Warning**
>
> 此 PR 的改动来自：<https://github.com/halo-dev/halo/pull/3498>
> 因为目前 Console 仓库已经合并到 Halo 主仓库，但主仓库的 release-2.3 分支不包含 Console，所以如果需要发布 2.3.x 的 patch 版本，依旧需要在此仓库修改。
/milestone 2.3.2
支持强制保存文章和单页面的设置，绕开后端 version 锁的机制，因为目前发现在后端 Reconcile 处理文章较慢时会影响文章的保存。
需要注意的是，这是一个不太合理的处理方式，但目前别无选择。
Fixes https://github.com/halo-dev/halo/issues/3339
测试方式：
1. 同时打开多个同文章的编辑页面的窗口。
2. 编辑任意一个窗口的文章设置。
3. 然后再去其他窗口保存，观察是否有异常。
```release-note
支持强制保存文章和页面的设置，避免因为 Version 锁的机制导致保存失败。
```

perf: add supports for force updating of post and single page settings
