halo-dev/console

- src/api/attachment.js
- src/views/system/OptionForm.vue
> 新增百度云oss文件上传下载功能

- .env
- .env.jsdelivr
- package.json
部署方案：
添加到 halo jar 包内：
```
npm run build-jsdelivr
```
> chore: add jsdelivr env.

- src/views/post/PostEdit.vue
- src/views/post/components/PostSettingDrawer.vue
- src/views/sheet/SheetEdit.vue
- src/views/sheet/components/SheetSettingDrawer.vue
修复如果文章保存/预览过程中失败，保存按钮不会恢复为可点击状态的问题。
> Fix post saving.

- src/views/post/PostList.vue
> Show quantity in category search in post list.

- src/components/editor/MarkdownEditor.vue
- src/views/post/PostEdit.vue
- src/views/sheet/SheetEdit.vue
将 Markdown 编辑器封装为组件，为以后添加富文本编辑器做准备。
> Pull out the markdown editor component.

- src/api/sheet.js
- src/components/editor/MarkdownEditor.vue
- src/components/editor/RichTextEditor.vue
- src/store/modules/option.js
- src/views/post/PostEdit.vue
- src/views/sheet/SheetEdit.vue
- src/views/system/OptionForm.vue
1. 目前只能去 `博客设置` 中的 `文章设置` 里修改默认编辑器。在编辑页面的切换按钮后面再加。
> Add rich text editor.

- src/views/system/About.vue
> Refactor about page.

- src/views/attachment/AttachmentList.vue
- src/views/attachment/components/AttachmentDetailDrawer.vue
- src/views/attachment/components/AttachmentDrawer.vue
- src/views/comment/components/CommentDetail.vue
- src/views/comment/components/CommentTab.vue
- src/views/comment/components/TargetCommentDrawer.vue
- src/views/dashboard/Dashboard.vue
- src/views/post/CategoryList.vue
- src/views/post/PostList.vue
- src/views/post/TagList.vue
- src/views/post/components/PostSettingDrawer.vue
- src/views/sheet/components/SheetSettingDrawer.vue
- src/views/sheet/internal/JournalList.vue
- src/views/sheet/internal/PhotoList.vue
- src/views/system/OptionForm.vue
- src/views/system/components/BackupDrawer.vue
- src/views/system/developer/tabs/OptionsList.vue
> Some text modification.

- src/views/post/components/PostSettingDrawer.vue
- src/views/sheet/components/SheetSettingDrawer.vue
> Refactor some copywriting.

- src/views/dashboard/components/LogListDrawer.vue
- src/views/interface/ThemeList.vue
> Fix the delete theme button could not be clicked.

- package-lock.json
- package.json
- src/components/Tools/UserMenu.vue
- src/components/editor/MarkdownEditor.vue
- src/views/attachment/AttachmentList.vue
- src/views/attachment/components/AttachmentSelectDrawer.vue
- src/views/dashboard/Dashboard.vue
- src/views/interface/ThemeList.vue
- src/views/post/CategoryList.vue
- src/views/post/PostEdit.vue
- src/views/post/PostList.vue
- src/views/post/TagList.vue
- src/views/post/components/PostSettingDrawer.vue
- src/views/sheet/SheetEdit.vue
- src/views/sheet/components/CustomSheetList.vue
- src/views/sheet/components/SheetSettingDrawer.vue
- src/views/sheet/internal/JournalList.vue
- src/views/sheet/internal/LinkList.vue
- src/views/sheet/internal/PhotoList.vue
- src/views/system/ToolList.vue
- src/views/system/developer/tabs/OptionsList.vue
- src/views/system/developer/tabs/RuntimeLogs.vue
- src/views/system/optiontabs/GeneralTab.vue
- src/views/system/optiontabs/PostTab.vue
- src/views/user/Profile.vue
一些小细节：
- 发布文章和更新文章的时候提示不准确。
- 发布按钮文字不准确。
> Refactor related functions for publishing posts.

- package-lock.json
- package.json
- src/api/migrate.js
- src/views/system/Installation.vue
> Support data import in install page.

- src/api/backup.js
- src/views/system/ToolList.vue
- src/views/system/components/BackupWorkDirDrawer.vue
- src/views/system/components/ExportDataDrawer.vue
> Support export database.

- src/views/system/components/BackupWorkDirDrawer.vue
- src/views/system/components/ExportDataDrawer.vue
> Fix backup download link cannot be clicked.

- src/api/log.js
- src/views/user/ResetPassword.vue
> Fix login typo.

- src/views/post/components/PostSettingDrawer.vue
> Refactor post settings drawer.

- src/components/SettingDrawer/SettingDrawer.vue
- src/components/Tools/UserMenu.vue
- src/layouts/BasicLayout.vue
- src/store/getters.js
- src/store/modules/app.js
- src/store/mutation-types.js
> Refactor layout setting drawer.

- src/api/admin.js
- src/api/user.js
- src/store/modules/user.js
- src/views/user/Login.vue
- src/views/user/Profile.vue
> Support MFA-TOTP Auth (halo #745)

- src/api/attachment.js
- src/views/system/optiontabs/AttachmentTab.vue
> 附件上传增加华为云OBS支持

- public/index.html
> feat: add renderer meta to index.html.

- package-lock.json
- package.json
- src/views/post/components/PostSettingDrawer.vue
- src/views/sheet/components/SheetSettingDrawer.vue
Resolved halo-dev/halo#807
Resolved halo-dev/halo#959
Resolved #121
> feat: support tiny-pinyin. #177

- package-lock.json
- package.json
- src/components/Attachment/AttachmentSelectDrawer.vue
- src/core/lazy_lib/components_use.js
- src/views/attachment/AttachmentList.vue
- src/views/attachment/components/AttachmentDetailDrawer.vue
- src/views/comment/components/CommentDetail.vue
- src/views/comment/components/CommentTab.vue
- src/views/interface/components/ThemeSettingDrawer.vue
- src/views/post/PostEdit.vue
- src/views/post/PostList.vue
- src/views/post/components/PostSettingDrawer.vue
- src/views/sheet/SheetEdit.vue
- src/views/sheet/components/SheetSettingDrawer.vue
- src/views/sheet/independent/JournalList.vue
- src/views/sheet/independent/PhotoList.vue
- src/views/system/components/BackupWorkDirDrawer.vue
- src/views/system/components/ExportDataDrawer.vue
- src/views/system/developer/tabs/ApplicationConfig.vue
- src/views/system/developer/tabs/OptionsList.vue
- src/views/system/developer/tabs/RuntimeLogs.vue
1. 采用了 Ant Design Vue 1.6.5 版本中的 Space 组件来分隔操作按钮。
> chore: upgrade dependencies.

- src/api/post.js
- src/utils/filter.js
- src/views/post/components/PostSettingDrawer.vue
- src/views/system/optiontabs/PermalinkTab.vue
同步后端 PR：https://github.com/halo-dev/halo/pull/1095
> feat: add post permalink type: YEAR

- src/api/theme.js
- src/views/interface/ThemeList.vue
issues https://github.com/halo-dev/halo/issues/995
> feat: 删除主题时可选是否删除配置

- src/views/system/optiontabs/PostTab.vue
后端 PR: https://github.com/halo-dev/halo/pull/1114
> feat: add automatic cleaning recycled posts configurations

- src/api/post.js
- src/views/post/components/PostSettingDrawer.vue
- src/views/system/optiontabs/PermalinkTab.vue
> feat: halo-dev/halo#1103

- src/api/sheet.js
- src/store/modules/option.js
- src/views/sheet/components/SheetSettingDrawer.vue
- src/views/system/optiontabs/PermalinkTab.vue
> feat: halo-dev/halo#1174

- src/views/system/optiontabs/PostTab.vue
> feat: #1101

- src/components/Login/LoginForm.vue
当开启 mfa 验证的时候，首次登陆会提示输入 mfa 验证码的问题。
> fix: mfa login.

- src/api/theme.js
> fix: halo-dev/halo#1180

- public/color.less
> fix: #219.

- package-lock.json
- package.json
- src/components/Button/ReactiveButton.vue
- src/components/Upload/FilePondUpload.vue
- src/styles/animate.less
- src/styles/style.less
- src/views/interface/ThemeList.vue
- src/views/system/Installation.vue
- src/views/system/ToolList.vue
- src/views/user/Login.vue
Resolve https://github.com/halo-dev/halo/issues/1213
> refactor: install page.

- src/views/post/PostEdit.vue
- src/views/sheet/SheetEdit.vue
> fix: post edit page.

- src/styles/global.less
> fix: 修复日志下长文本无法换行的问题

- src/views/system/optiontabs/GeneralTab.vue
取消对系统设置中 logo 和 favicon 的 url 类型验证，这种验证方式不支持相对路径形式的地址。
> pref: unvalidate url type for logo and favicon in system options.

- package-lock.json
- package.json
- src/components/Tools/HeaderComment.vue
- src/views/dashboard/Dashboard.vue
- src/views/interface/ThemeList.vue
- src/views/interface/components/MenuInternalLinkSelector.vue
- src/views/system/optiontabs/SmtpTab.vue
- yarn.lock
> refactor: disable tabs change animation.

- src/components/Login/LoginForm.vue
- src/utils/device.js
- src/views/user/Login.vue
> fix: login page keyboard shortcut keys not working in macOS.

- src/views/sheet/SheetEdit.vue
- src/views/sheet/components/CustomSheetList.vue
- src/views/sheet/components/SheetSettingModal.vue
> refactor: sheet setting modal

- src/views/system/Installation.vue
> refactor: installation page logo

- src/utils/api-client.js
支持优先从 localstorage 获取 apiUrl。
Close #387
> feat: support get api url from localstorage

- .env.jsdelivr
- README.md
- package.json
- public/index.html
> release: 1.4.16

- README.md
> docs: add repobeats analytics image to readme

- src/components/Editor/MarkdownEditor.vue
> fix: failed to upload picture in the markdown editor #400

- src/views/user/ResetPassword.vue
> refactor: form validation of the reset password page

- .env.jsdelivr
- README.md
- package.json
- public/index.html
> release: 1.4.17

- package.json
- pnpm-lock.yaml
- src/components/Tools/HeaderComment.vue
- src/views/comment/components/CommentTab.vue
- src/views/comment/components/TargetCommentTree.vue
- src/views/dashboard/components/RecentCommentTab.vue
- src/views/system/About.vue
升级 marked 依赖以解决安全性问题。https://github.com/halo-dev/halo-admin/security/dependabot/package.json/marked/open
> fix: upgrade marked to fix security issues

- .gitpod.yml
- README.md
> chore: add gitpod config file

- .vscode/extensions.json
- .vscode/settings.json
> chore: add vscode config file

- src/views/interface/ThemeList.vue
- src/views/interface/components/ThemeInstallModal.vue
> refactor: theme install modal

- src/views/system/About.vue
关于页面贡献者列表中的头像来源使用 @n0vad3v 提供的 https://webp.se
> perf: the contributor avatar source for the about page uses webp.se

- src/views/user/Profile.vue
|before|after |
|![image](https://user-images.githubusercontent.com/21301288/150085537-3d3861fb-ab73-4d4f-a3fe-5ffec3b57f28.png)|![image](https://user-images.githubusercontent.com/21301288/150085477-71290031-1efe-4cb8-b6f4-b79b00b339f7.png)|
> refactor: profile form input width

- src/components/Comment/CommentListView.vue
- src/components/Tools/HeaderComment.vue
- src/components/index.js
- src/filters/filter.js
- src/styles/global.less
- src/views/dashboard/Dashboard.vue
- src/views/dashboard/components/RecentCommentTab.vue
> refactor: pending review status comment component

- public/index.html
- src/utils/domUtil.js
页面标题改为 Halo，原来的 Halo Dashboard 不准确。
> refactor: modify the page title suffix

- src/views/post/components/TagSelect.vue
选择标签的列表排序改为根据名称排序。 Close #428 
> feat: select the list of tags sorted by name

- src/views/interface/ThemeSetting.vue
|before|after |
|<img width="1544" alt="image" src="https://user-images.githubusercontent.com/21301288/153157228-6fcfa616-a3fa-4c64-b15a-9d711dda0d62.png">|<img width="1544" alt="image" src="https://user-images.githubusercontent.com/21301288/153157128-c4babfc9-6874-45d6-b023-38257e704ac0.png">|
> perf: unify the font color of the description in the theme settings

- src/views/post/CategoryList.vue
- src/views/post/components/CategorySelectTree.vue
- src/views/post/components/CategoryTreeNode.vue
|before|after |
|<img width="1800" alt="image" src="https://user-images.githubusercontent.com/21301288/154193962-7d7bc1c2-ec69-4c51-8bc7-836355f1911e.png">|<img width="1800" alt="image" src="https://user-images.githubusercontent.com/21301288/154193885-87409873-d2ff-4296-869b-9fa1502d465c.png">|
> refactor: post category management

- package.json
- pnpm-lock.yaml
- src/views/post/CategoryList.vue
- src/views/post/components/CategoryTreeNode.vue
1. 分类支持拖动排序。
see https://deploy-preview-442--adoring-jang-01641c.netlify.app/
> feat: post category support sorting

- src/views/post/PostList.vue
> refactor: post list tag rendering using PostTag component

- src/views/post/PostList.vue
- src/views/sheet/components/CustomSheetList.vue
> fix: the title of draft post list cannot be displayed

- src/core/constant.js
- src/views/post/PostList.vue
> refactor: post list component code optimization

- src/core/constant.js
- src/views/sheet/components/CustomSheetList.vue
> refactor: custom sheet list component code optimization

- package.json
- pnpm-lock.yaml
changlog:
https://github.com/halo-dev/editor/compare/df7a70c0b74a7f367276615b06927ae05fb66fbf...09f7115e09ac42bdb3fa469e5b59fddbbd26dc3f
> chore: bump @halo-dev/editor to 3.0.0-alpha.1

- package.json
Try to release 1.5.0-alpha.1
- 使用 @halo-dev/admin-api 进行接口请求。 halo-dev/halo-admin#378 @ruibaby @guqing
- 修改后台页面标题后缀，由 `Halo Dashboard` 改为 `Halo`。 halo-dev/halo-admin#426 @ruibaby
- 默认后台布局改为左侧菜单布局。 halo-dev/halo-admin#441 @ruibaby
- 重构文章/自定义页面编辑逻辑，改为保存前端渲染内容，放弃后端渲染。 halo-dev/halo-admin#439 halo-dev/halo-admin#440 halo-dev/halo-admin#449 @ruibaby
- 文章标签支持设置颜色。 halo-dev/halo-admin#395 @ruibaby @guqing
- 文章设置界面支持重新生成别名。 halo-dev/halo-admin#368 @ruibaby
- 更新 Logo。 halo-dev/halo-admin#366 @ruibaby
- 重构主题设置界面，提供单独的设置页面，支持展示主题的相关信息。 halo-dev/halo-admin#380 @ruibaby
- 弱化登录页面的动画效果。 halo-dev/halo-admin#369 @ruibaby
- 优化附件管理列表预览图片样式。 halo-dev/halo-admin#374 halo-dev/halo-admin#382 @felix @cetr
- 重构附件详情界面，取消原有抽屉的设计，改为弹窗。 halo-dev/halo-admin#375 halo-dev/halo-admin#381 @ruibaby
- …
> release: 1.5.0-alpha.1

- .env.jsdelivr
- package.json
> chore: remove build for jsdelivr env

- src/styles/style.less
> perf: improve login form style

- .env
- src/views/interface/ThemeSetting.vue
Change the subject material link to '_blank'
> Change the target of the link in the theme description to _blank

- package.json
- pnpm-lock.yaml
- src/styles/global.less
Fix #457 
related https://github.com/halo-dev/editor/commit/c9334d0166471c717a27b650573e4269a8b1b786
~~等待 @halo-dev/editor 发布版本，并在此 PR 升级到修复版本。~~
> Fix the problem of abnormal ui when the editor is switched to full screen

- package.json
- pnpm-lock.yaml
- src/styles/global.less
- src/views/sheet/independent/PhotoList.vue
- src/views/sheet/independent/components/PhotoFormModal.vue
Close #466 
---
before: 
支持批量操作：
支持批量修改分组：
支持批量从附件库添加：
更方便的修改图片：
支持在列表显示分组：
> Refactor photo management

- src/components/Comment/TargetCommentTreeNode.vue
- src/styles/global.less
- src/views/comment/CommentList.vue
- src/views/comment/components/CommentTab.vue
- src/views/sheet/independent/JournalList.vue
Close https://github.com/halo-dev/halo/issues/305
> feat: comment management page adds a list of comments to the journal

- package.json
> release: 1.5.0-alpha.2

- src/components/Category/CategoryCreateModal.vue
- src/components/Post/PostSettingModal.vue
> feat: support new categories in post settings

- src/config/defaultSettings.js
> perf: update localStorage namespace

- package.json
- pnpm-lock.yaml
- src/components/Tools/Logo.vue
Close #483 
修复点击后台 Halo Logo 进入开发者选项过快会导致计数为负的情况。
> fix: the problem of incorrect hint of opening developer option

- package.json
```markdown
- 文章设置弹框支持创建新分类。 halo-dev/halo-admin#489 @ruibaby
- 优化后台折叠菜单的体验，解决折叠时 Logo 和 菜单动画不同步的问题。 halo-dev/halo-admin#493 @ruibaby
- 缓存后台折叠菜单的状态，刷新页面不再会恢复到初始状态。 halo-dev/halo-admin#493 @ruibaby
- 优化后台判断是否初始化的逻辑，修改为每次页面加载只请求一次，切换路由不再请求。 halo-dev/halo-admin#495 @ruibaby
- 修改全局的 Local Storage 的前缀，修复 alpha.2 中因为后台布局配置变化导致升级后布局混乱的问题。 halo-dev/halo-admin#490 @ruibaby
- 修复点击后台 Halo Logo 进入开发者选项过快可能会导致计数为负的问题。 halo-dev/halo-admin#492 @ruibaby
- 修复附件列表分页之后，可能会导致无法正常更新图片 dom 导致图片显示为上一页图片的问题。 halo-dev/halo-admin#496 @ruibaby
```
> release: 1.5.0-alpha.3

- src/views/interface/MenuList.vue
> feat: support to modify menu team name

- .eslintrc.cjs
- package.json
- pnpm-lock.yaml
- postcss.config.js
- src/main.ts
- src/styles/tailwind.css
- src/views/HomeView.vue
- tailwind.config.js
> chore: configure tailwind css

- package.json
```markdown
- 菜单分组支持修改分组名。 halo-dev/halo-admin#499 @ruibaby
- 个人资料头像修改支持输入链接。 halo-dev/halo-admin#505 @ruibaby
- 重构主题设置保存预览功能。 halo-dev/halo-admin#502 @ruibaby
- 重构日志发布表单，使用 Markdown 编辑器替换 textarea，并支持保存前端渲染的 Markdown 结果。 halo-dev/halo-admin#506 @ruibaby
- 修复分类/标签/友情链接修改表单切换修改对象之后没有清除表单验证的问题。 halo-dev/halo-admin#501 halo-dev/halo-admin#503 @Yorksh1re
- 更新 @halo-dev/editor 版本。 halo-dev/halo-admin#507 @ruibaby
- 修复嵌套列表语法的渲染问题。
- 添加 attrs 和 mark 语法的插件。
- 优化列表语法的编写，可以自动添加序号。
- 添加打开图片选择的快捷键。
- 统一使用 @halo-dev/markdown-renderer 库进行 Markdown 渲染。
```
> release: 1.5.0-beta.1

- src/views/interface/ThemeVisualSetting.vue
- src/views/interface/components/ThemeSettingForm.vue
> feat: theme visual settings page add back button

- .github/workflows/main.yml
> chore: add unit test github action steps

- src/components/SettingDrawer/SettingDrawer.vue
> fix: wrong path to referenced image

- src/components/Post/PostSettingModal.vue
> fix: the mode.topPriority involving computed is not initialized

- src/views/system/optiontabs/SmtpTab.vue
> fix: error message of sending email test

- src/components/Post/PostSettingModal.vue
fixes halo-dev/halo#1776
/kind bug
> fix: initial value of topPriority in post settings

- package.json
```
- 修复菜单管理 `从系统预设链接添加菜单` 中选择独立页面无法创建菜单的问题。 halo-dev/halo-admin#520 @QuentinHsu
- 修复后台布局设置中，`亮色菜单风格` 所使用的图标不正确的问题。 halo-dev/halo-admin#524 @QuentinHsu @wangzhen-fit2cloud
- 修复首次创建文章时是否置顶按钮无法切换的问题。 halo-dev/halo-admin#525 halo-dev/halo-admin#530 @QuentinHsu @ruibaby @guqing
- 修复在 SMTP 设置中测试邮件发送时，提示有误的问题。 halo-dev/halo-admin#526 @QuentinHsu @hapke24
- 修复分类管理中当父分类为加密状态时，超过第二级子分类没有显示加密状态的问题。 halo-dev/halo-admin#527
- 更新 @halo-dev/editor 版本。 halo-dev/halo-admin#529 @ruibaby
- 统一编辑器字体在各个系统的表现。
- 修复使用中文输入法的时候，候选框挡住当前行文字的问题。
```
> release: 1.5.1

- package.json
- pnpm-lock.yaml
修复点击导航菜单项无法滚动到指定预览区域的问题。
/kind bug
> chore: bump @halo-dev/editor to resolve navigation issue

- src/components/Category/CategoryTree.vue
> perf: categories in the post settings supports showing whether there is a password or not

- package.json
```markdown
- 后台文章设置中选择分类列表支持显示加密状态。 halo-dev/halo-admin#540 @ruibaby
- 后台文章管理中分类筛选列表支持显示加密状态。 halo-dev/halo-admin#541 @ruibaby
- 修复后台仪表盘统计中图标显示不完整的问题。 halo-dev/halo-admin#536 @ruibaby
- 修复后台页面切换时长超过 250ms 的时候不显示加载条的问题。 halo-dev/halo-admin#539 @ruibaby
- 修复后台文章回收站列表文章标题无法显示完整的问题。 halo-dev/halo-admin#537 @ruibaby
- 修复后台分类列表当没有数据的时候不显示空状态的问题。 halo-dev/halo-admin#538 @ruibaby
- 重构后台主题色切换逻辑，修复切换主题色之后，部分样式异常的问题。 halo-dev/halo-admin#543 @ruibaby
- 更新后台 @halo-dev/editor 版本。 halo-dev/halo-admin#535 @ruibaby
- 修复点击导航菜单项无法滚动到指定预览区域的问题。
```
> release: 1.5.2

- src/views/dashboard/Dashboard.vue
> fix: abnormal style due to long title of recent posts in the dashboard

- OWNERS
> chore: create OWNERS file

- src/views/dashboard/Dashboard.vue
- src/views/interface/ThemeSetting.vue
- src/views/interface/components/ThemeSettingForm.vue
主题设置页面顶部添加了个保存设置按钮
before：
after:
> perf: add a button to save the settings in the actions area of the theme settings page

- src/components/Post/PostListView.vue
- src/views/attachment/AttachmentList.vue
- src/views/comment/components/CommentTab.vue
- src/views/dashboard/Dashboard.vue
- src/views/sheet/components/CustomSheetList.vue
- src/views/sheet/independent/JournalList.vue
- src/views/system/developer/tabs/OptionsList.vue
> perf: under the list, after deleting all the data on the current page, query the data on the previous page

- README.md
目前已经关闭 halo-dev/halo-admin 的 Issues 功能，后续将统一在 halo-dev/halo 管理。
> docs: update README.md for issue feedback

- package.json
```markdown
- 优化后台部分弹窗中表单在移动端的布局。 halo-dev/halo-admin#564 @ruibaby
- 修复后台仪表盘中最近文章的标题过长导致样式异常的问题。 halo-dev/halo-admin#545 @Aanko @hotspring-zwb
- 修复后台带有分页的数据列表中，删除最后一页的所有数据后导致分页页码异常的问题。 halo-dev/halo-admin#550 @QuentinHsu @luohongqu
- 修复后台修复因为缓存数据，重新安装会出现循环进入 install 路由的问题。 halo-dev/halo-admin#558 @ruibaby  @Ljfanny
- 更新后台 @halo-dev/editor 版本。 halo-dev/halo-admin#562 @ruibaby
- 修复在改变编辑器布局后导致重复初始化编辑器的问题。
```
> release: 1.5.3

- src/views/user/Profile.vue
didn't find approporiate kind
fix typo
none
```release-note
None
```
> fix typo: profile email message typo.

- public/index.html
/kind cleanup
/kind deprecation
zh-cmn-Hans is marked as deprecated.
https://www.iana.org/assignments/language-subtag-registry/language-subtag-registry
NONE
For compatibility, `zh-Hans` or `zh-Hans-CN` are better choices, they are not deprecated.
```release-note
Replace zh-cmn-Hans with cmn-Hans
```
> Replace zh-cmn-Hans with cmn-Hans

- package.json
- pnpm-lock.yaml
- src/components/Attachment/AttachmentSelectModal.vue
- src/styles/global.less
- src/views/attachment/AttachmentList.vue
- src/views/sheet/independent/PhotoList.vue
- tailwind.config.js
/milestone 1.6.x
1. 之前的布局没有适配多设备或者超分屏的情况。
2. 由于固定了单个附件项的高度，所以会导致图片变形。
3. 使用的 background 属性来显示图片，会导致图片失效或者无法显示的时候显示空白。
此 PR 采用 TailwindCSS + [@tailwindcss/aspect-ratio](https://github.com/tailwindlabs/tailwindcss-aspect-ratio) 的方案固定长宽比。
Fixes halo-dev/halo#2159
Before:
After:
```release-note
None
```
> refactor: attachment list layout

- package.json
- packages/shared/.eslintrc.cjs
- packages/shared/env.d.ts
- packages/shared/package.json
- packages/shared/prettier.config.js
- packages/shared/src/index.ts
- packages/shared/src/types/menus.ts
- packages/shared/src/types/plugin.ts
- packages/shared/tsconfig.app.json
- packages/shared/tsconfig.json
- packages/shared/tsconfig.vite-config.json
- packages/shared/tsconfig.vitest.json
- packages/shared/vite.config.ts
- pnpm-lock.yaml
/kind feature
添加 @halo-dev/admin-shared 包，此包主要提供：
1. Admin Core 以及插件所需的类型定义。
2. Admin Core 以及插件都会用到的业务组件。
使用方式：
```bash
npm install @halo-dev/admin-shared
yarn add @halo-dev/admin-shared
pnpm install @halo-dev/admin-shared
```
```ts
import type { Plugin } from '@halo-dev/admin-shared'
const plugin: Plugin {
}
```
Fixes #
None
目前仅创建了这个包并设置基础配置，并未实现具体功能。
```release-note
None
```
> feat: create admin-shared package

- package.json
- pnpm-lock.yaml
升级 `@halo-dev/editor` 的版本。
- https://github.com/halo-dev/editor/pull/5
- https://github.com/halo-dev/editor/pull/4
Fixes #
None
```release-note
升级 `@halo-dev/editor` 的版本至 3.0.5。
```
> chore: bump editor version to 3.0.5

- package.json
Fixes #
```markdown
- 移除前端对附件访问地址的 encodeURI 处理，改为由后端提供实际可访问地址。halo-dev/halo-admin#568 [@FanZeros](https://github.com/FanZeros) [@qaiu](https://github.com/qaiu)
- 修复新建分类中父级分类选择列表过长导致的 UI 问题。 halo-dev/halo-admin#577 [@SladeGranger](https://github.com/SladeGranger) [@Alickx](https://github.com/Alickx)
- 更新 @halo-dev/editor 版本。 halo-dev/halo-admin#584 [@ruibaby](https://github.com/ruibaby)
- 优化预览/编辑按钮的提示文案。 halo-dev/editor#4 [@manction](https://github.com/manction)
- 修复编辑器的滚动条会与添加链接面板有重叠的问题。 halo-dev/editor#5 [@wxyShine](https://github.com/wxyShine) [@zyy247796143](https://github.com/zyy247796143)
```
```release-note
None
```
> release: 1.5.4

- pnpm-lock.yaml
- src/components/Post/PostTag.vue
- src/views/post/TagList.vue
/kind feature
/milestone 1.6.x
支持清理没有被文章使用的标签
Fixes halo-dev/halo#2203
/ping @halo-dev/sig-halo-admin 
```release-note
支持清理没有被文章使用的标签
```
> feat: add cleanup tags support

- .github/workflows/main.yml
- Dockerfile
/kind feature
/milestone 2.0
Add build-push job for admin project. This job will produce docker image `ghcr.io/halo-dev/admin-dev`.
```release-note
None
```
> Add build-push job for Halo admin

- packages/shared/package.json
- packages/shared/src/utils/api-client.ts
- pnpm-lock.yaml
- src/modules/system/plugins/PluginList.vue
- src/modules/system/plugins/components/PluginInstallModal.vue
/kind feature
/milestone 2.0
添加上传插件的支持。
see https://github.com/halo-dev/halo/pull/2271
None
可以使用以下插件仓库中 Actions 构建的 JAR 测试：
- https://github.com/halo-sigs/plugin-links/actions
- https://github.com/halo-sigs/plugin-meilisearch/actions
- https://github.com/halo-sigs/plugin-template/actions
/cc @halo-dev/sig-halo 
```release-note
None
```
> feat: add support for uploading plugins

- package.json
- packages/shared/package.json
- pnpm-lock.yaml
- src/modules/system/plugins/PluginDetail.vue
- src/modules/system/plugins/PluginList.vue
- src/modules/system/roles/RoleList.vue
- src/modules/system/roles/composables/use-role.ts
/kind feature
/milestone 2.0
适配 https://github.com/halo-dev/halo/pull/2279
接口支持通过参数筛选数据。
None
None
/hold until https://github.com/halo-dev/halo/pull/2279 merge
```release-note
None
```
> feat: api supports field filtering

- package.json
- packages/shared/package.json
- packages/shared/src/utils/api-client.ts
- pnpm-lock.yaml
- src/modules/interface/themes/ThemeDetail.vue
- src/modules/interface/themes/components/ThemeListModal.vue
- src/modules/interface/themes/composables/use-theme.ts
/kind feature
/milestone 2.0
添加基础的主题管理支持，适配 https://github.com/halo-dev/halo/pull/2280
/hold until https://github.com/halo-dev/halo/pull/2280 merge
None
|<img width="1564" alt="image" src="https://user-images.githubusercontent.com/21301288/182314023-546d5fe1-03bb-4c7e-af36-6730ab051931.png">|<img width="1564" alt="image" src="https://user-images.githubusercontent.com/21301288/182314339-6c13b60a-cddc-449d-a06f-faaa53f76335.png">|
|<img width="1564" alt="image" src="https://user-images.githubusercontent.com/21301288/182314487-4c551208-938c-4582-bce6-7f589f278e8f.png">|      |
None
```release-note
None
```
> feat: add support for theme management

- package.json
- packages/shared/package.json
- packages/shared/src/utils/api-client.ts
- pnpm-lock.yaml
- src/modules/interface/themes/components/ThemeInstallModal.vue
- src/modules/interface/themes/components/ThemeListModal.vue
/kind feature
/milestone 2.0
新增主题上传支持，适配 https://github.com/halo-dev/halo/pull/2302
/hold until https://github.com/halo-dev/halo/pull/2302 merge
Fixes halo-dev/halo#2291
```release-note
None
```
> feat: add theme install support

- package.json
- packages/shared/package.json
- pnpm-lock.yaml
- src/modules/interface/themes/components/ThemeListModal.vue
/kind feature
/milestone 2.0
支持卸载主题，适配 https://github.com/halo-dev/halo/pull/2315
Fixes https://github.com/halo-dev/halo/issues/2306
None
/hold until https://github.com/halo-dev/halo/issues/2306 merge
```release-note
None
```
> feat: add theme uninstall support

- src/components/GlobalFooter/GlobalFooter.vue
用 powered 更加合适
```release-note
NONE
```
> typo: power to powered

- pnpm-lock.yaml
/kind optimization
update caniuse-lite for browserslist
Fixes #
```release-note
NONE
```
> chore: update caniuse-lite for browserslist

- src/views/sheet/independent/JournalList.vue
- src/views/sheet/independent/LinkList.vue
- src/views/sheet/independent/PhotoList.vue
/kind bug
修复了无法设置日志、相册、链接页标题和每页显示条数的Bug
Fixes halo-dev/halo#2366
Fixes halo-dev/halo#2339
None
```release-note
None
```
> fix: failed to set journal page size option

- package.json
- packages/shared/package.json
- pnpm-lock.yaml
- src/modules/contents/posts/PostList.vue
- src/modules/contents/posts/categories/CategoryList.vue
- src/modules/contents/posts/categories/composables/use-post-category.ts
- src/modules/contents/posts/components/PostSettingModal.vue
- src/modules/contents/posts/tags/TagList.vue
- src/modules/contents/posts/tags/composables/use-post-tag.ts
- src/modules/interface/menus/components/MenuItemEditingModal.vue
- src/modules/interface/menus/components/MenuItemListItem.vue
/kind feature
/milestone 2.0
菜单项支持设置与文章、分类、标签的关联关系。关联之后，当被关联对象有所改变时，同步菜单项更新。适配：https://github.com/halo-dev/halo/pull/2380
> 自定义页面（pageRef）会等到 https://github.com/halo-dev/halo/pull/2381 合并之后再做适配。
Fixes https://github.com/halo-dev/halo/issues/2295
/hold until https://github.com/halo-dev/halo/pull/2380 merge
```release-note
None
```
> feat: menu items support setting ref relations

- package.json
- packages/shared/package.json
- pnpm-lock.yaml
- src/modules/interface/menus/components/MenuItemEditingModal.vue
- src/modules/interface/menus/components/MenuItemListItem.vue
/kind feature
/milestone 2.0
菜单项支持绑定自定义页面。适配 https://github.com/halo-dev/halo/pull/2395
功能测试步骤：
1. 本地仓库 Checkout 到当前 PR。
2. Halo 后端需要 Checkout 到 https://github.com/halo-dev/halo/pull/2395/files PR。
3. 更新依赖：pnpm install
4. 构建依赖包：pnpm build:packages
5. 进入后台的自定义页面并新建页面。
6. 进入菜单管理，添加类型为自定义页面的菜单项。
7. 检查最终菜单项提供的显示名称和 permalink 是否正确。
8. 修改页面标题或者 slug，再检查最终菜单项的显示名称和 permalink 是否有自动修改。
/hold until https://github.com/halo-dev/halo-admin/pull/606 merge
```release-note
None
```
> feat: menu items support setting singlePage ref relations

- src/components/entity/Entity.vue
- src/components/entity/EntityField.vue
- src/modules/contents/attachments/AttachmentList.vue
- src/modules/contents/pages/FunctionalPageList.vue
- src/modules/contents/pages/SinglePageList.vue
- src/modules/contents/posts/PostList.vue
- src/modules/contents/posts/categories/components/CategoryListItem.vue
- src/modules/contents/posts/tags/TagList.vue
- src/modules/interface/menus/components/MenuItemListItem.vue
- src/modules/interface/menus/components/MenuList.vue
- src/modules/system/plugins/components/PluginListItem.vue
- src/modules/system/roles/RoleList.vue
- src/modules/system/users/UserList.vue
/kind feature
/milestone 2.0
添加 Entity 和 EntityField 组件，作为列表项使用。
测试方式：检查后台各个页面的列表样式和功能是否正常。
```release-note
None
```
> feat: add the entity component as a list item

- package.json
- packages/shared/src/utils/api-client.ts
- pnpm-lock.yaml
/milestone 2.0
适配 https://github.com/halo-dev/halo/pull/2419
Fixes https://github.com/halo-dev/halo/issues/2418
具体变更请查阅：https://github.com/halo-dev/halo/pull/2419
```release-note
None
```
> refactor: rename api group for custom api

- package.json
- pnpm-lock.yaml
- src/modules/interface/themes/ThemeDetail.vue
/kind feature
/milestone 2.0
支持重载主题设置，以便开发主题的时候重载配置。适配 https://github.com/halo-dev/halo/pull/2456
Fixes halo-dev/halo#2426
```release-note
None
```
> feat: add reload theme setting support

- package.json
- pnpm-lock.yaml
- src/modules/contents/pages/SinglePageList.vue
/kind feature
/milestone 2.0
自定义页面管理支持筛选，适配 https://github.com/halo-dev/halo/pull/2481
Fixes https://github.com/halo-dev/halo/issues/2469
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/2481 PR 的分支。
3. 创建多个自定义页面。
4. 测试筛选功能是否符合预期
```release-note
自定义页面管理支持筛选
```
> feat: singlePage management adds filtering support

- package.json
- pnpm-lock.yaml
- src/modules/contents/posts/PostList.vue
- src/modules/contents/posts/categories/components/CategoryListItem.vue
- src/modules/contents/posts/tags/TagList.vue
/milestone 2.0
修改标签/分类显示文章数量的字段。 适配 https://github.com/halo-dev/halo/pull/2483
Fixes #
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/2483 PR 中的分支。
3. 发布多篇带分类和标签的文章后，检查分类和标签的文章数量是否正确。
```release-note
None
```
> refactor: update the field for the number of post under categories and tags

- package.json
- pnpm-lock.yaml
- src/modules/system/plugins/PluginList.vue
/kind feature
/milestone 2.0
添加插件管理筛选的支持。适配 https://github.com/halo-dev/halo/pull/2489
Fixes https://github.com/halo-dev/halo/issues/2470
/cc @halo-dev/sig-halo 
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/2489 PR 的分支。
3. 安装若干插件，测试筛选和排序。
```release-note
插件管理支持筛选
```
> feat: add plugin filters support

- src/router/guards/check-states.ts
- src/router/index.ts
- src/router/routes.config.ts
- src/stores/system-states.ts
- src/views/system/Setup.vue
- src/views/system/setup-data/category.json
- src/views/system/setup-data/menu-items.json
- src/views/system/setup-data/menu.json
- src/views/system/setup-data/post.json
- src/views/system/setup-data/singlePage.json
- src/views/system/setup-data/tag.json
/kind feature
/milestone 2.0
支持初始化默认数据。
Fixes https://github.com/halo-dev/halo/issues/2428
测试方式：
1. 清空数据库。
2. 启动之后登录即可跳转到初始化界面。
3. 测试初始化的功能是否正常。
```release-note
None
```
> feat: add system setup support

- src/main.ts
- src/modules/contents/attachments/AttachmentList.vue
- src/modules/contents/attachments/components/AttachmentGroupList.vue
- src/modules/contents/attachments/module.ts
- src/modules/contents/comments/CommentList.vue
- src/modules/contents/comments/components/CommentListItem.vue
- src/modules/contents/comments/components/ReplyListItem.vue
- src/modules/contents/comments/module.ts
- src/modules/contents/pages/SinglePageList.vue
- src/modules/contents/pages/layouts/PageLayout.vue
- src/modules/contents/pages/module.ts
- src/modules/contents/posts/PostList.vue
- src/modules/contents/posts/categories/CategoryList.vue
- src/modules/contents/posts/categories/components/CategoryListItem.vue
- src/modules/contents/posts/module.ts
- src/modules/contents/posts/tags/TagList.vue
- src/modules/dashboard/widgets/QuickLinkWidget.vue
- src/modules/interface/menus/Menus.vue
- src/modules/interface/menus/components/MenuEditingModal.vue
- src/modules/interface/menus/components/MenuItemListItem.vue
- src/modules/interface/menus/components/MenuList.vue
- src/modules/interface/menus/module.ts
- src/modules/interface/themes/ThemeDetail.vue
- src/modules/interface/themes/components/ThemeListModal.vue
- src/modules/interface/themes/layouts/ThemeLayout.vue
- src/modules/interface/themes/module.ts
- src/modules/system/plugins/components/PluginListItem.vue
- src/modules/system/roles/RoleList.vue
- src/modules/system/users/UserList.vue
- src/utils/permission.ts
/kind feature
/milestone 2.0
完善 UI 权限控制。适配 https://github.com/halo-dev/halo/pull/2488
Fixes https://github.com/halo-dev/halo/issues/2342
测试方式：
1. Halo 需要使用 https://github.com/halo-dev/halo/issues/2342 PR 的分支。
2. 创建新的角色，并勾选需要测试的权限。
3. 创建新的用户并赋予新的角色。
4. 测试操作权限。
```release-note
完善 UI 权限控制
```
> feat: refine ui permissions

- README.md
/milestone 2.0
更新 README
```release-note
None
```
> docs: update readme for Halo 2.0

- src/main.ts
- src/modules/contents/attachments/AttachmentList.vue
- src/modules/contents/comments/components/CommentListItem.vue
- src/modules/contents/pages/SinglePageList.vue
- src/modules/contents/posts/PostList.vue
- src/modules/contents/posts/tags/components/PostTag.vue
- src/modules/interface/menus/components/MenuItemListItem.vue
- src/modules/interface/menus/components/MenuList.vue
- src/modules/interface/themes/components/ThemeListModal.vue
- src/modules/system/plugins/components/PluginListItem.vue
- src/modules/system/roles/RoleList.vue
- src/modules/system/users/UserList.vue
修复 UI 权限的问题。
/kind bug
/milestone 2.0
```release-note
None
```
> fix: ui permissions

- src/components/Attachment/AttachmentSelectModal.vue
- src/views/sheet/independent/PhotoList.vue
/kind feature
优化后台图库批量添加图片的排序方式
Fixes https://github.com/halo-dev/halo/issues/2487
1. 添加了徽标用于展示添加图片的顺序，参考：https://1x.antdv.com/components/badge-cn/#API
2. 按照图片添加顺序进行排序
```release-note
所有页面-图库-选择附件界面添加了徽标，用于展示添加图片的顺序
```
> perf: batch add to photos in order of image selection

- package.json
发布 1.5.5
```markdown
修复了无法设置日志、相册、链接页标题和每页显示条数的问题 halo-dev/console#601 @JustinLiang522
```
```release-note
None
```
> release: 1.5.5

- package.json
/milestone 1.6.x
发布 1.6.0
```markdown
- 后台附件设置中添加 `去除图片 EXIF 信息` 的选项。 halo-dev/console#554 @SladeGranger
- 后台文章标签管理支持清理未使用标签。 halo-dev/console#587 @ruibaby
- 重构后台的友情链接管理页面，现在支持拖动排序以及分组管理。 halo-dev/console#574 @gungnir479
- 后台在构建时提供 gzip 压缩的资源。 halo-dev/console#547 @2211898719
- 后台主题设置界面顶部提供了保存设置的按钮。 halo-dev/console#549 @Aanko
- 修改后台页面的 lang 属性，由 `zh-cmn-Hans` 改为 `cmn-Han`，`zh-cmn-Hans` 已废弃。 halo-dev/console#576 @wordlesswind
- 优化后台附件库列表以及选择附件弹框的布局。 halo-dev/console#580 @ruibaby
- 修改后台底部的 `Power by Halo` 为 `Powered by Halo`。 halo-dev/console#597 @liaocp666
- 优化后台日志管理设置公开/隐藏状态的方式。 halo-dev/console#610 @zjy4fun @manction
- 优化后台在个人资料中设置头像的逻辑，现在无需再提交个人资料表单。 halo-dev/console#619 @wxyShine
- 优化后台图库批量从附件添加时，按照选择顺序倒序排列，即最先选择的图片在最前面。 halo-dev/console#631 @zjy4fun @zyy247796143
- …
```
> release: 1.6.0

- Makefile
/kind feature
/area console
```bash
╰─❯ make help 
all                  lint and test code
install              install dependencies
build                build console
lint                 lint code
test                 run tests
help                 print this help
```
```release-note
None
```
> Add Makefile for convenient operations

- package.json
- pnpm-lock.yaml
- src/modules/contents/pages/SinglePageList.vue
- src/modules/contents/posts/PostList.vue
- src/modules/dashboard/widgets/RecentPublishedWidget.vue
- src/modules/dashboard/widgets/ViewsStatsWidget.vue
/kind api-change
/kind bug
更新 `@halo-dev/api-client` 以修复文章访问数据不正确的问题。
```release-note
更新 `@halo-dev/api-client` 以修复文章访问数据不正确的问题。
```
> chore: bump @halo-dev/api-client for post stats

- package.json
- src/components/Post/PostTag.vue
- src/views/sheet/independent/PhotoList.vue
- src/views/user/Profile.vue
bug
to fix the parenthesis problem of article list labels
Fixes #
Before：
After：
```release-note
优化文章列表标签显示
```
> fix: post list showing the number of post in the tags

- packages/components/package.json
- packages/shared/package.json
/milestone 2.0
发布 `@halo-dev/components` `@halo-dev/console-shared` 版本。
```release-note
None
```
> chore: bump packages version

- src/modules/interface/themes/ThemeDetail.vue
- src/modules/interface/themes/components/ThemeListModal.vue
- src/modules/interface/themes/components/ThemeUploadModal.vue
/kind feature
/milestone 2.0
支持升级主题。适配 https://github.com/halo-dev/halo/pull/2600
Fixes https://github.com/halo-dev/halo/issues/2550
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/2600
2. 需要 `pnpm install`
3. 测试更主题功能是否正常。
```release-note
支持升级主题。
```
> feat: add upgrade theme support

- packages/components/src/icons/icons.ts
- src/modules/contents/attachments/AttachmentList.vue
- src/modules/contents/comments/CommentList.vue
- src/modules/contents/pages/SinglePageList.vue
- src/modules/contents/posts/PostList.vue
- src/modules/system/plugins/PluginList.vue
/kind feature
/milestone 2.0
为部分功能数据列表添加刷新按钮。
测试方式：
1. 需要 `pnpm build:packages`
2. 测试点击刷新按钮是否可以正常请求接口。
```release-note
为部分功能数据列表添加刷新按钮。
```
> feat: add a refresh button to the data list

- src/modules/interface/themes/ThemeDetail.vue
- src/modules/system/plugins/components/PluginListItem.vue
- src/modules/system/plugins/layouts/PluginLayout.vue
/milestone 2.0
插件和主题管理的 Logo 改为使用 `Avatar` 组件。
测试方式：检查主题和插件相关的管理页面是否正常加载 Logo。
```release-note
插件和主题管理的 Logo 改为使用 `Avatar` 组件。
```
> refactor: load the theme and plugin logos using the avatar component

- .husky/pre-commit
/milestone 2.0
移除在 Git Commit 之前运行单元测试和类型检查的步骤。因为目前 main 分支处于保护分支，无法直接推送代码。所以仅在 PR 中的 Action 来运行这两个步骤即可。
```release-note
None
```
> chore: remove the step to run unit tests and typecheck before git commit

- README.md
更新 [Repobeats analytics](https://repobeats.axiom.co/) 的图片源，之前因为修改仓库名，导致 Repobeats analytics 的统计失效。
```release-note
None 
```
> docs: update repobeats analytics images source for readme file

- src/layouts/BasicLayout.vue
- src/modules/interface/themes/components/ThemeListModal.vue
- src/modules/interface/themes/components/ThemeUploadModal.vue
- src/modules/system/users/Login.vue
- src/views/system/Setup.vue
- vite.config.ts
- vitest.config.ts
/milestone 2.0
以 inline svg 的形式加载 Logo，解决因为加载 svg 文件导致的页面抖动问题。
测试方式：检查登录页面、初始化页面、侧边菜单顶部的 Logo 是否加载正常。
```release-note
以 inline svg 的形式加载 Logo，解决因为加载 svg 文件导致的页面抖动问题。
```
> refactor: load the logo as an inline svg

- package.json
- packages/shared/package.json
/milestone 2.0
发布 2.0.0-alpha.3
从此版本开始，`@halo-dev/console-shared` 包的版本与 Console 始终保持一致。
```release-note
None
```
> chore: release 2.0.0-alpha.3

- src/formkit/theme.ts
- src/modules/contents/comments/components/ReplyCreationModal.vue
- src/modules/contents/pages/components/SinglePageSettingModal.vue
- src/modules/contents/posts/components/PostSettingModal.vue
- src/modules/interface/themes/ThemeSetting.vue
- src/modules/system/plugins/PluginSetting.vue
- src/modules/system/settings/SystemSetting.vue
- src/modules/system/users/layouts/UserProfileLayout.vue
/milestone 2.0
优化表单的样式。
before:
after:
```release-note
优化表单的样式。
```
> perf: improve the layout and style of forms

- src/modules/contents/pages/SinglePageList.vue
- src/modules/contents/posts/PostEditor.vue
- src/modules/contents/posts/PostList.vue
/kind bug
/milestone 2.0
文章列表中显示的时间改为发布时间（`post.spec.publishTime`）。
Fixes https://github.com/halo-dev/halo/issues/2642
```release-note
文章列表中显示的时间改为发布时间
```
> fix: show publish time instead of creation time for post list

- src/modules/contents/pages/DeletedSinglePageList.vue
- src/modules/contents/pages/SinglePageList.vue
- src/modules/contents/pages/layouts/PageLayout.vue
- src/modules/contents/pages/module.ts
- src/modules/contents/posts/DeletedPostList.vue
- src/modules/contents/posts/PostList.vue
- src/modules/contents/posts/module.ts
/kind feature
/milestone 2.0
支持管理已删除的文章和自定义页面，优化删除的逻辑。
Fixes https://github.com/halo-dev/halo/issues/2647
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/2648
2. 测试文章和自定义页面的删除功能，以及回收站的管理功能。
```release-note
支持管理已删除的文章和自定义页面，优化删除的逻辑。
```
> feat: support for managing recycle bin posts and single pages

- src/formkit/theme.ts
/milestone 2.0
优化表单中关于 fieldset 的样式。
Fixes https://github.com/halo-dev/halo/issues/2655
before:
after:
```release-note
优化表单中关于 fieldset 的样式。
```
> perf: optimize the style of fieldset in the form

- package.json
- packages/shared/package.json
/milestone 2.0
发布 Halo 2.0 第四个 alpha 版本的 Console 部分。
```release-note
None
```
> chore: release 2.0.0-alpha.4

- src/main.ts
- src/router/guards/check-states.ts
- src/views/system/Setup.vue
/milestone 2.0
重构获取系统初始化状态的方式，之前会在每个路由切换前获取，在一定程度上会导致路由切换时卡顿。此 PR 改为仅在首次加载页面的时候调用接口获取，并保留状态由 pinia 管理。
测试方式：
1. 需要使用未初始化的 Halo。
2. 测试在未初始化前是否会自动切换到初始化页面。
3. 测试初始化之后是否还会跳转到初始化页面。
```release-note
None
```
> refactor: refactoring the logic for get the setup state of the system

- package.json
- pnpm-lock.yaml
- src/modules/contents/attachments/composables/use-attachment.ts
- src/modules/contents/comments/CommentList.vue
- src/modules/contents/pages/DeletedSinglePageList.vue
- src/modules/contents/pages/SinglePageList.vue
- src/modules/contents/posts/DeletedPostList.vue
- src/modules/contents/posts/PostEditor.vue
- src/modules/contents/posts/PostList.vue
- src/modules/contents/posts/components/PostSettingModal.vue
- src/modules/system/plugins/PluginList.vue
- src/modules/system/users/UserList.vue
/milestone 2.0
重构文章发布/取消发布/放入回收站的逻辑。适配 https://github.com/halo-dev/halo/pull/2675
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/2675 的分支。
2. Console 需要 `pnpm install`。
3. 测试文章发布/取消发布/放入回收站。
```release-note
None
```
> refactor: post publishing

- package.json
- packages/components/package.json
- packages/shared/package.json
/milestone 2.0
发布 Console 2.0.0-beta.1
```release-note
None
```
> chore: release 2.0.0-beta.1

- package.json
- packages/components/package.json
- packages/shared/package.json
/milestone 2.0
发布 Console 2.0.0-beta.2
```release-note
None
```
> chore: release 2.0.0-beta.2

- src/components/filter/FilterCleanButton.vue
- src/components/filter/FilterTag.vue
- src/components/tag/FilterTag.vue
- src/modules/contents/attachments/AttachmentList.vue
- src/modules/contents/attachments/composables/use-attachment.ts
- src/modules/contents/comments/CommentList.vue
- src/modules/contents/comments/components/CommentListItem.vue
- src/modules/contents/pages/DeletedSinglePageList.vue
- src/modules/contents/pages/SinglePageList.vue
- src/modules/contents/posts/DeletedPostList.vue
- src/modules/contents/posts/PostList.vue
- src/modules/system/plugins/PluginList.vue
/milestone 2.0
优化 Console 数据列表的筛选标签样式，以及支持清空所有筛选条件。
Fixes https://github.com/halo-dev/halo/issues/2657
测试方式：
1. 测试文章、自定义页面、附件、插件、评论管理中的筛选功能。
```release-note
优化 Console 数据列表的筛选标签样式，以及支持清空所有筛选条件。
```
> perf: improve the list filter style and support clear all

- src/layouts/BasicLayout.vue
- src/main.ts
- src/modules/dashboard/widgets/QuickLinkWidget.vue
- src/modules/system/users/Login.vue
- src/modules/system/users/UserList.vue
- src/modules/system/users/components/UserPasswordChangeModal.vue
- src/router/guards/auth-check.ts
- src/stores/user.ts
/milestone 2.0
使用 Pinia 管理已授权用户信息，并提供判断是否是 `anonymousUser` 的方式。
适配 https://github.com/halo-dev/halo/pull/2729
测试流程：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/2729 的分支。
2. 测试 Console 端的登录、退出等流程。
```release-note
None
```
> refactor: managing logged-in user states with pinia

- packages/components/src/components.ts
- packages/components/src/components/loading/Loading.vue
- packages/components/src/components/loading/index.ts
- src/modules/contents/attachments/AttachmentList.vue
- src/modules/contents/comments/CommentList.vue
- src/modules/contents/pages/DeletedSinglePageList.vue
- src/modules/contents/pages/SinglePageList.vue
- src/modules/contents/posts/DeletedPostList.vue
- src/modules/contents/posts/PostList.vue
- src/modules/contents/posts/categories/CategoryList.vue
- src/modules/contents/posts/tags/TagList.vue
- src/modules/interface/menus/Menus.vue
- src/modules/interface/menus/components/MenuList.vue
- src/modules/interface/themes/ThemeDetail.vue
- src/modules/interface/themes/ThemeSetting.vue
- src/modules/interface/themes/components/ThemeListModal.vue
- src/modules/interface/themes/layouts/ThemeLayout.vue
- src/modules/system/plugins/PluginDetail.vue
- src/modules/system/plugins/PluginList.vue
- src/modules/system/plugins/PluginSetting.vue
- src/modules/system/plugins/layouts/PluginLayout.vue
- src/modules/system/roles/RoleList.vue
- src/modules/system/settings/SystemSetting.vue
- src/modules/system/settings/layouts/SystemSettingsLayout.vue
- src/modules/system/users/UserList.vue
- src/setup/setupStyles.ts
- src/styles/index.css
/milestone 2.0
优化列表的加载，添加加载动画，解决加载完成之后界面闪动的问题。
Ref https://github.com/halo-dev/halo/issues/2370
```release-note
优化列表的加载，添加加载动画，解决加载完成之后界面闪动的问题。
```
> refactor: add loading states for data list

- src/components/dropdown-selector/CategoryDropdownSelector.vue
- src/components/dropdown-selector/TagDropdownSelector.vue
- src/modules/contents/posts/PostList.vue
/milestone 2.0
优化文章管理的分类/标签/作者的筛选下拉框样式，以及支持搜索。
测试方式：检查文章管理的分类 / 标签 / 作者筛选功能是否正常。
```release-note
优化文章管理的分类/标签/作者的筛选下拉框样式，以及支持搜索。
```
> perf: filter dropdown selector

- src/modules/contents/attachments/AttachmentList.vue
- src/modules/contents/attachments/composables/use-attachment.ts
- src/modules/contents/comments/CommentList.vue
- src/modules/contents/comments/components/CommentListItem.vue
- src/modules/contents/pages/DeletedSinglePageList.vue
- src/modules/contents/pages/SinglePageList.vue
- src/modules/contents/posts/PostList.vue
- src/modules/contents/posts/categories/composables/use-post-category.ts
- src/modules/contents/posts/tags/composables/use-post-tag.ts
- src/modules/interface/menus/Menus.vue
- src/modules/interface/menus/components/MenuList.vue
- src/modules/interface/themes/components/ThemeListModal.vue
- src/modules/system/plugins/PluginList.vue
/kind bug
/milestone 2.0
修复因为 https://github.com/halo-dev/console/pull/703 中添加了 Loading 动画但是没有考虑到定时刷新列表导致页面闪动的问题。
测试方式：删除任意资源，检查列表定时刷新的时候是否出现 loading 状态。
```release-note
None
```
> fix: splash screen issue caused by refreshing the list at regular intervals

- src/modules/contents/pages/SinglePageEditor.vue
- src/modules/contents/posts/PostEditor.vue
/milestone 2.0
首次创建文章或者自定义页面时，跳转回管理列表，与编辑保持一致。
测试方式：创建一篇新的文章或自定义页面，点击发布，观察是否返回到了管理列表。
```release-note
None
```
> perf: back to post list when post is first created

- package.json
- packages/components/package.json
- packages/shared/package.json
/milestone 2.0
修改版本号以发布 Console 2.0.0-rc.1
```release-note
None
```
> chore: release 2.0.0-rc.1

- OWNERS
将 @Aanko 添加到 Reviewer 列表。
```release-note
None
```
> chore: add @Aanko to reviewer list

- package.json
- pnpm-lock.yaml
- src/components/editor/DefaultEditor.vue
升级 `@halo-dev/richtext-editor` 版本以支持图片放大缩小、嵌入网页、表格。
Fixes https://github.com/halo-dev/halo/issues/2681
测试方式：
2. 测试编辑器的图片放大缩小、嵌入网页、表格等功能。
```release-note
Console 端编辑器支持图片放大缩小、嵌入网页、表格。
```
> chore: bump @halo-dev/richtext-editor version

- package.json
- pnpm-lock.yaml
- src/modules/interface/themes/ThemeDetail.vue
- src/modules/interface/themes/components/ThemeListModal.vue
/kind api-change
/milestone 2.0
升级 `@halo-dev/api-client` 以适配 https://github.com/halo-dev/halo/pull/2745
Fixes https://github.com/halo-dev/halo/issues/2735
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/issues/2735 分支。
3. 安装一个主题，并尝试修改 `theme.yaml` 和 `settings.yaml`，然后再主题详情页面点击 `刷新设置表单` 的按钮，检查改动是否被更新。
```release-note
None
```
> chore: bump @halo-dev/api-client for reload theme api

- src/layouts/BasicLayout.vue
- src/modules/contents/attachments/components/AttachmentGroupList.vue
- src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
- src/modules/contents/comments/CommentList.vue
- src/modules/contents/comments/components/CommentListItem.vue
- src/modules/contents/comments/components/ReplyListItem.vue
- src/modules/contents/pages/DeletedSinglePageList.vue
- src/modules/contents/pages/SinglePageList.vue
- src/modules/contents/posts/DeletedPostList.vue
- src/modules/contents/posts/PostList.vue
- src/modules/interface/themes/ThemeDetail.vue
- src/modules/interface/themes/components/ThemeListModal.vue
- src/modules/system/plugins/composables/use-plugin.ts
- src/modules/system/roles/RoleList.vue
- src/modules/system/users/UserList.vue
/milestone 2.0
修改了各个删除操作提示弹框的信息，统一了文本风格。
原本存在 `是否确认删除xxx？` 和 `确定删除xxx吗？` 两种风格，统一为后一种风格。
```release-note
优化 Console 端确认弹框的提示文案。
```
> perf: unify the copywriting style of confirms

- src/modules/system/roles/RoleDetail.vue
- src/modules/system/roles/RoleList.vue
移除角色详情页面的用户列表，当前后端暂不支持通过角色查询其下用户。
None
```release-note
None
```
> perf: remove the list of users under role details

- package.json
- pnpm-lock.yaml
- src/modules/contents/attachments/AttachmentList.vue
- src/modules/contents/attachments/components/AttachmentDetailModal.vue
- src/modules/contents/attachments/components/AttachmentGroupList.vue
- src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
- src/modules/contents/attachments/components/AttachmentPolicyEditingModal.vue
- src/modules/contents/attachments/components/AttachmentUploadModal.vue
/milestone 2.0
重构附件、存储策略、附件分组之间的关联方式。适配：https://github.com/halo-dev/halo/pull/2800
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/2800 分支。
3. 测试附件相关功能。
```release-note
None
```
> refactor: simplify references in Attachment

- package.json
- pnpm-lock.yaml
- src/modules/interface/menus/components/MenuItemEditingModal.vue
- src/modules/interface/menus/components/MenuItemListItem.vue
/milestone 2.0
重构菜单项关联关系的引用方式。适配：https://github.com/halo-dev/halo/pull/2799
Fixes https://github.com/halo-dev/halo/issues/2739
测试方式：
1. Halo 需要切换到 https://github.com/halo-dev/halo/pull/2799 分支。
3. 创建若干带有关联关系的菜单项，检查创建和更新是否正常。
```release-note
None
```
> refactor: simplify MenuItem with targetRef instead of multi refs

- src/utils/api-client.ts
/kind feature
/milestone 2.0
添加全局的请求异常提示。
Fixes https://github.com/halo-dev/halo/issues/2370
```release-note
添加全局的请求异常提示。
```
> feat: add global request error toast

- src/views/exceptions/Forbidden.vue
- src/views/exceptions/NotFound.vue
- src/views/exceptions/components/Exception.vue
/kind feature
/milestone 2.0
完善 Console 端的 404/403 页面。
Fixes https://github.com/halo-dev/halo/issues/2597
None
```release-note
完善 Console 端的 404/403 页面。
```
> feat: add exception pages

- src/main.ts
- src/stores/system-states.ts
/milestone 2.0
在首次初始化页面隐藏 `资源不存在` 的提示，这是由 https://github.com/halo-dev/console/pull/732 带来的问题。
测试方式：
1. 准备全新的环境。
2. 进入初始化页面，检查是否存在 `资源不存在` 的提示。
```release-note
None
```
> perf: hide toast on setup page

- src/views/system/Setup.vue
- src/views/system/setup-data/menu-items.json
- src/views/system/setup-data/post.json
- src/views/system/setup-data/singlePage.json
/milestone 2.0
更新系统初始化数据的资源，主要为了适配 https://github.com/halo-dev/console/pull/730 的修改。
测试方式：
1. 准备全新的环境。
2. 启动之后初始化，检查初始数据是否正常。
```release-note
None
```
> perf: refine setup data and logic of post publish

- package.json
- packages/components/package.json
- packages/shared/package.json
修改版本号以发布 Console 2.0.0 正式版。
```release-note
None
```
> chore: release 2.0.0

- src/modules/interface/themes/ThemeDetail.vue
/kind bug
修改主题升级文案
Fixes https://github.com/halo-dev/halo/issues/2857
```release-note
None
```
> perf: improve the text of the upgrade theme button

- src/stores/theme.ts
/kind bug
修复在生产环境，激活主题之后，界面数据没有更新的问题。
Fixes https://github.com/halo-dev/halo/issues/2850
测试方式：
1. 使用 `pnpm build` 构建此 PR。
2. 在 Halo 配置 `halo.console.location` 为 Console 项目的 dist 目录，比如：`file:/Users/ryanwang/Workspace/github/ruibaby/halo-console/dist/`
3. 安装若干主题，激活其中一个，检查页面 UI 元素是否更新。
```release-note
修复 Console 端激活主题之后页面没有更新数据的问题。
```
> fix: ui is not updated after the theme is activated in the production

- src/modules/interface/themes/ThemeDetail.vue
- src/modules/interface/themes/ThemeSetting.vue
- src/modules/system/plugins/PluginDetail.vue
- src/modules/system/plugins/PluginSetting.vue
- src/modules/system/settings/SystemSetting.vue
- src/modules/system/settings/layouts/SystemSettingsLayout.vue
优化主题和插件详情页面切换 tab 时的页面闪动问题。
Fixes https://github.com/halo-dev/halo/issues/2856
测试方式：检查在主题和插件详情页面是否还存在 https://github.com/halo-dev/halo/issues/2856 中提到的问题。
```release-note
优化 Console 端的主题和插件详情页面切换选项卡时的页面闪动问题。
```
> perf: optimize the issue of animation when switching setting tabs

- src/modules/contents/attachments/AttachmentList.vue
- src/modules/contents/comments/CommentList.vue
- src/modules/contents/pages/SinglePageList.vue
- src/modules/contents/posts/PostList.vue
- src/modules/system/plugins/PluginList.vue
- src/modules/system/users/components/UserEditingModal.vue
部分 UI 元素使用了图标代替文字，但某些情况下可能会导致无法直观的判断具体用途，添加 tooltip 以提示使用者。
Fixes https://github.com/halo-dev/halo/issues/2656
```release-note
Console 端为部分图标按钮添加操作提示，提升可访问性。
```
> perf: add tooltip for some icon buttons

- README.md
see https://github.com/badges/shields/issues/8671
```release-note
None
```
> docs: update github workflow badge

- package.json
- packages/shared/package.json
/milestone 2.0.2
发布 Console 2.0.2。
```release-note
None
```
> chore: bump version for Halo 2.0.2

- src/modules/system/plugins/components/PluginListItem.vue
- src/modules/system/plugins/composables/use-plugin.ts
合并卸载插件的选项。
Fixes https://github.com/halo-dev/halo/issues/2978
before:
after:
测试方式：
1. 测试插件卸载的两种选项是否功能正常。
```release-note
优化 Console 端的插件卸载选项布局
```
> perf: merge plugin uninstallation options button

- src/modules/system/settings/SystemSetting.vue
- src/modules/system/settings/layouts/SystemSettingsLayout.vue
/kind bug
修复系统设置页面切换选项卡无法正常加载表单的问题。
Fixes https://github.com/halo-dev/halo/issues/3001
测试方式：
1. 测试系统设置页面的选项卡切换和保存功能。
```release-note
修复 Console 端系统设置页面切换选项卡无法正常加载表单的问题。
```
> fix: system settings form could not be loaded

- src/modules/contents/pages/DeletedSinglePageList.vue
移除自定义页面回收站中自定义页面的固定链接跳转入口。
```release-note
None
```
> perf: remove permalink of deleted single page

- packages/components/src/components/entity/EntityField.vue
- src/modules/contents/posts/DeletedPostList.vue
- src/modules/contents/posts/PostList.vue
优化文章管理列表的布局，修复当分类设置过多时的样式问题。
Fixes https://github.com/halo-dev/halo/issues/2963
测试方式：
1. 添加若干个文字数量较多的分类。
2. 观察文章列表的样式是否有问题。
```release-note
优化 Console 端文章管理列表的布局，修复当分类设置过多时的样式问题。
```
> perf: improve the layout of the post list

- src/modules/system/roles/RoleList.vue
- src/modules/system/roles/composables/use-role.ts
- src/modules/system/users/UserList.vue
/milestone 2.1.x
优化用户和角色列表，如果包含正在删除的内容会自动刷新。
Fixes https://github.com/halo-dev/halo/issues/3036
测试方式：
1. 创建若干角色和用户。
2. 测试删除之后是否会自动刷新列表。
```release-note
优化 Console 端的用户和角色列表，如果包含正在删除的内容会自动刷新。
```
> perf: automatic refresh of the list of users and roles

- src/modules/system/roles/components/RoleEditingModal.vue
/milestone 2.1.x
重构角色编辑的表单，取消多选项卡的设计。
Fixes https://github.com/halo-dev/halo/issues/3033
测试方式：
1. 测试新建和编辑角色。
2. 检查功能是否符合预期。
```release-note
重构 Console 端角色编辑的表单，取消多选项卡的设计。
```
> refactor: layouts of role editing form

- package.json
- pnpm-lock.yaml
- src/modules/system/users/components/UserEditingModal.vue
移除使用 yaml 编辑用户信息的功能。
Fixes https://github.com/halo-dev/halo/issues/3046
None
```release-note
移除 Console 端使用 yaml 编辑用户信息的功能
```
> refactor: remove the ability to edit user using yaml

- package.json
- packages/shared/package.json
发布 Console 2.1.0-rc.1
Ref https://github.com/halo-dev/halo/issues/3050
```release-note
None
```
> chore: release 2.1.0-rc.1

- src/modules/system/users/Login.vue
/kind bug
修复在 Safari 浏览器登录之后无反应的问题。
Fixes https://github.com/halo-dev/halo/issues/3002
测试方式：
1. 在 Safari 浏览器上测试登录之后是否有跳转到仪表盘即可。
```release-note
修复 Console 端在 Safari 浏览器登录之后无反应的问题
```
> fix: login in safari browser has no effect

- src/modules/contents/pages/components/SinglePageSettingModal.vue
- src/modules/contents/posts/components/PostSettingModal.vue
/kind bug
修复保存文章设置导致发布时间丢失的问题。
see https://github.com/halo-dev/console/pull/807
Fixes https://github.com/halo-dev/halo/issues/3080
测试方式：
1. 创建若干文章。
2. 返回到文章管理列表。
3. 打开任意文章的设置。
4. 检查发布时间是否回显，然后保存。
5. 保存之后检查发布时间是否还存在。
```release-note
修复 Console 端保存文章设置导致发布时间丢失的问题。
```
> fix: saving an post causes the publish time to be lost

- package.json
- packages/shared/package.json
For Console 2.0.3 release. See https://github.com/halo-dev/halo/issues/3078 for more.
Fixes https://github.com/halo-dev/halo/issues/3078
```release-note
None
```
> Bump Console to 2.0.3

- package.json
- packages/shared/package.json
发布 Console 2.1.0
Ref https://github.com/halo-dev/halo/issues/3077
```release-note
None
```
> chore: release 2.1.0

- src/components/login/LoginForm.vue
/kind optimization
remove login form icon, fix icon lose dev tool console warning
Fixes  https://github.com/halo-dev/halo/issues/3071
```release-note
NONE
```
> fix: remove login form icon, fix icon lose warning

- src/components/upload/UppyUpload.vue
Remove the timeout error prompt caused by the upload server processing for more than 30 seconds
Fixes https://github.com/halo-dev/halo/issues/3041
测试：
上传大文件让后端处理过程超过30秒，观察是否报错
或使用[修改后的插件](https://github.com/longjuan/halo-plugin-s3os/actions/runs/3852075387)上传到对象存储，观察61秒后是否上传成功
```release-note
去除上传文件处理时间超过30秒后的报错
```
> fix: timeout error caused by upload processing for more than 30 seconds

- src/layouts/BasicLayout.vue
/kind feature
将侧边栏的 Logo 链接到首页。
Fixes https://github.com/halo-dev/halo/issues/2847
```release-note
支持点击 Console 侧边栏 Logo 跳转到首页
```
> feat: make sidebar logo link to home page

- src/modules/contents/attachments/AttachmentList.vue
目前暂时没有缩略图功能，上传大量的大型图片很容易造成浏览器崩溃，故我们临时将附件管理的默认视图模式改为列表模式。
Fixes https://github.com/halo-dev/halo/issues/3167
```release-note
Console 附件管理的默认视图模式改为列表模式。
```
> perf: change attachment list layout to list mode

- .npmrc
- package.json
- pnpm-lock.yaml
- src/components/editor/DefaultEditor.vue
- src/modules/contents/attachments/composables/use-attachment.ts
/kind feature
升级默认编辑器版本，改动请查阅：
1. https://github.com/halo-sigs/richtext-editor/pull/4
2. https://github.com/halo-sigs/richtext-editor/pull/3
3. https://github.com/halo-sigs/richtext-editor/pull/2
```release-note
升级 Console 端默认编辑器版本，以支持图片位置和大小设置、插入音视频等功能。
```
> chore: bump @halo-dev/richtext-editor to supports more feature about media

- package.json
- packages/components/package.json
- packages/shared/package.json
发布 Console 2.2.0
```release-note
None
```
> chore: release 2.2.0

- src/utils/api-client.ts
/area console
添加`X-Requested-With=XMLHttpRequest`请求头，以阻止spring security 带上`WWW-Authenticate`响应头导致弹出原生登录框。
Fixes https://github.com/halo-dev/halo/issues/3213
使session过期后（直接删除cookie的session或重启后端），继续操作console端，预期不会弹出原生登录框且console端原有的重新登录form正常弹出。
详情https://spring.io/guides/tutorials/spring-security-and-angular-js/ 中搜索X-Requested-With
```release-note
防止浏览器弹出原生登录框
```
> fix: native login box pops up when the session expires

- src/modules/system/actuator/Actuator.vue
修复 Actuator 页面抖动的问题。
Fixes https://github.com/halo-dev/halo/issues/3225
测试方式：
1. 测试进入系统概览页面是否会出现 https://github.com/halo-dev/halo/issues/3225 中提到的页面抖动问题。
```release-note
修复 Console 端进入系统概览页面会抖动的问题。
```
> perf: fix CLS issue of actuator page

- src/modules/system/users/UserList.vue
在用户管理列表隐藏 anonymousUser 用户，anonymousUser 暂时没有实际用途。
Fixes https://github.com/halo-dev/halo/issues/2775#issuecomment-1425129852
测试方式：
1. 进入 Console 的用户管理，检查是否有名为 Anonymous User 的用户即可。
```release-note
在 Console 端的用户管理中隐藏 `Anonymous User` 用户。
```
> perf: hide anonymousUser in user management list

- src/components/editor/DefaultEditor.vue
- src/modules/dashboard/widgets/QuickLinkWidget.vue
移除未使用的导入和变量。
```release-note
None
```
> chore: fix lint issue

- OWNERS
将 @LIlGG 添加到 Reviewer 列表。
```release-note
None
```
> chore: add @LIlGG to reviewers list

- src/stores/role.ts
静默请求所有角色信息，用于显示 displayName。（临时解决方案）
```release-note
None
```
> perf: mute the fetch roles request

- package.json
- packages/shared/package.json
发布 Console 2.2.1 版本。
```release-note
None
```
> chore: release 2.2.1

- packages/components/src/components/dialog/Dialog.story.vue
- src/components/form/AnnotationsForm.vue
- src/modules/contents/attachments/composables/use-attachment.ts
- src/modules/contents/comments/CommentList.vue
- src/modules/contents/comments/components/CommentListItem.vue
- src/modules/contents/comments/components/ReplyListItem.vue
- src/modules/contents/posts/categories/CategoryList.vue
- src/modules/contents/posts/components/PostSettingModal.vue
- src/modules/interface/menus/Menus.vue
- src/modules/system/users/components/GrantPermissionModal.vue
调整部分日志级别，以及删除部分无用的日志。
```release-note
None
```
> chore: adjust the log level and delete useless logs

- src/modules/system/actuator/Actuator.vue
/kind feature
在系统概览页面支持下载运行日志。
Fixes https://github.com/halo-dev/halo/issues/3188
测试方式：
1. 进入系统概览页面，点击运行日志的下载按钮。
2. 检查是否成功下载了日志文件。
```release-note
Console 端的系统概览页面支持下载运行日志。
```
> feat: add supports for download log file in actuator page

- src/modules/system/users/UserList.vue
What type of PR is this?
/kind bug
What this PR does / why we need it:
将ghost用户从用户列表隐藏。
Which issue(s) this PR fixes:
Fixes https://github.com/halo-dev/halo/issues/3317
```release-note
NONE
```
> fix: hide the ghost user from the user list

- src/modules/contents/posts/DeletedPostList.vue
- src/modules/contents/posts/PostList.vue
优化文章管理列表的标签布局，改为单独占用一行。
Fixes https://github.com/halo-dev/halo/issues/2926
Fixes https://github.com/halo-dev/halo/issues/3301
```release-note
优化 Console 端文章管理的标签布局
```
> perf: improve the layout of post tags

- package.json
- pnpm-lock.yaml
- src/locales/index.ts
- src/locales/lang/zh.ts
- src/main.ts
- src/modules/system/roles/RoleDetail.vue
- src/modules/system/roles/components/RoleEditingModal.vue
/kind feature
为系统内提供的角色模板提供中文翻译。
Fixes https://github.com/halo-dev/halo/issues/2848
测试方式：
2. 检查角色详情页面和新建页面的角色模板描述是否为中文。
```release-note
Console 端为系统内提供的角色模板提供中文翻译
```
> feat: provide Chinese translation for the system's role template

- src/components/editor/DefaultEditor.vue
- src/modules/contents/attachments/AttachmentList.vue
- src/modules/contents/attachments/components/AttachmentDetailModal.vue
- src/modules/contents/attachments/components/AttachmentGroupList.vue
- src/modules/contents/attachments/components/AttachmentPoliciesModal.vue
- src/modules/contents/attachments/components/AttachmentUploadModal.vue
- src/modules/contents/attachments/components/selector-providers/CoreSelectorProvider.vue
- src/modules/contents/attachments/composables/use-attachment-group.ts
- src/modules/contents/attachments/composables/use-attachment-policy.ts
- src/modules/contents/attachments/composables/use-attachment.ts
使用 [TanStack Query](https://github.com/TanStack/query) 重构附件相关数据请求的相关逻辑。
Ref https://github.com/halo-dev/halo/issues/3360
测试方式：
1. 测试附件管理页面的筛选、存储策略、分组等业务。
2. 测试附件选择模态框组件。
```release-note
None
```
> refactor: use tanstack query to refactor attachments-related fetching

- packages/api-client/src/models/comment-spec.ts
- packages/api-client/src/models/reply-spec.ts
- src/modules/contents/comments/components/CommentListItem.vue
- src/modules/contents/comments/components/ReplyListItem.vue
修改评论和回复的创建时间字段。适配：https://github.com/halo-dev/halo/pull/3341
Fixes https://github.com/halo-dev/halo/issues/3330
None
```release-note
None
```
> refactor: change the creation time field for comments and replies

- package.json
- packages/api-client/package.json
- packages/shared/package.json
/milestone 2.3.x
发布 2.3.0-rc.1
```release-note
None
```
> chore: release 2.3.0-rc.1

- package.json
- pnpm-lock.yaml
- src/build/library-external.ts
/kind bug
修复在生产环境中，使用了 TanStack Query 的页面无法正常加载的问题。
测试方式：
1. 编译 Console 。
2. 配置 Halo 的 `halo.console.location` 为 Console 项目的 dist 目录。
3. 访问 Console，检查各个页面是否能够正常加载。
```release-note
None
```
> fix: pages using tanstack query cannot be loaded in production build

- src/modules/interface/themes/ThemeSetting.vue
- src/modules/interface/themes/components/preview/ThemePreviewModal.vue
- src/modules/system/plugins/PluginSetting.vue
保存主题和插件设置时，添加保存成功的反馈提示。
None
```release-note
None
```
> perf: add success toast for saving plugin and theme settings

- package.json
- packages/api-client/package.json
- packages/components/package.json
- packages/shared/package.json
/milestone 2.3.0
发布 2.3.0。
```release-note
None
```
> chore: release 2.3.0

- README.md
目前此仓库已经合并到了 Halo 主仓库，所以现在修改 README 以提示。
```release-note
None
```
> docs: update readme for repo migration

- package.json
- packages/api-client/package.json
- packages/shared/package.json
发布 Console 2.3.1。
```release-note
None
```
> chore: release 2.3.1

- package.json
- packages/api-client/package.json
- packages/shared/package.json
发布 Console 2.3.2
```release-note
None
```
> chore: release 2.3.2
